// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agents/v1/dashboard.proto

package agentsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.orx.me/apps/butter/pkg/proto/agents/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DashboardServiceName is the fully-qualified name of the DashboardService service.
	DashboardServiceName = "agents.v1.DashboardService"
	// DaemonServiceName is the fully-qualified name of the DaemonService service.
	DaemonServiceName = "agents.v1.DaemonService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DashboardServiceGetOverviewProcedure is the fully-qualified name of the DashboardService's
	// GetOverview RPC.
	DashboardServiceGetOverviewProcedure = "/agents.v1.DashboardService/GetOverview"
	// DashboardServiceGetActivityFeedProcedure is the fully-qualified name of the DashboardService's
	// GetActivityFeed RPC.
	DashboardServiceGetActivityFeedProcedure = "/agents.v1.DashboardService/GetActivityFeed"
	// DaemonServiceListDaemonsProcedure is the fully-qualified name of the DaemonService's ListDaemons
	// RPC.
	DaemonServiceListDaemonsProcedure = "/agents.v1.DaemonService/ListDaemons"
	// DaemonServiceGetDaemonProcedure is the fully-qualified name of the DaemonService's GetDaemon RPC.
	DaemonServiceGetDaemonProcedure = "/agents.v1.DaemonService/GetDaemon"
	// DaemonServiceCancelDaemonTaskProcedure is the fully-qualified name of the DaemonService's
	// CancelDaemonTask RPC.
	DaemonServiceCancelDaemonTaskProcedure = "/agents.v1.DaemonService/CancelDaemonTask"
)

// DashboardServiceClient is a client for the agents.v1.DashboardService service.
type DashboardServiceClient interface {
	// GetOverview returns aggregate counts, component health and the latest
	// daemon handshake for the dashboard Overview screen.
	GetOverview(context.Context, *connect.Request[v1.GetOverviewRequest]) (*connect.Response[v1.GetOverviewResponse], error)
	// GetActivityFeed returns the most recent invocation activity, oldest event
	// first stripped, suitable for the dashboard Activity Feed widget.
	GetActivityFeed(context.Context, *connect.Request[v1.GetActivityFeedRequest]) (*connect.Response[v1.GetActivityFeedResponse], error)
}

// NewDashboardServiceClient constructs a client for the agents.v1.DashboardService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDashboardServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DashboardServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dashboardServiceMethods := v1.File_agents_v1_dashboard_proto.Services().ByName("DashboardService").Methods()
	return &dashboardServiceClient{
		getOverview: connect.NewClient[v1.GetOverviewRequest, v1.GetOverviewResponse](
			httpClient,
			baseURL+DashboardServiceGetOverviewProcedure,
			connect.WithSchema(dashboardServiceMethods.ByName("GetOverview")),
			connect.WithClientOptions(opts...),
		),
		getActivityFeed: connect.NewClient[v1.GetActivityFeedRequest, v1.GetActivityFeedResponse](
			httpClient,
			baseURL+DashboardServiceGetActivityFeedProcedure,
			connect.WithSchema(dashboardServiceMethods.ByName("GetActivityFeed")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dashboardServiceClient implements DashboardServiceClient.
type dashboardServiceClient struct {
	getOverview     *connect.Client[v1.GetOverviewRequest, v1.GetOverviewResponse]
	getActivityFeed *connect.Client[v1.GetActivityFeedRequest, v1.GetActivityFeedResponse]
}

// GetOverview calls agents.v1.DashboardService.GetOverview.
func (c *dashboardServiceClient) GetOverview(ctx context.Context, req *connect.Request[v1.GetOverviewRequest]) (*connect.Response[v1.GetOverviewResponse], error) {
	return c.getOverview.CallUnary(ctx, req)
}

// GetActivityFeed calls agents.v1.DashboardService.GetActivityFeed.
func (c *dashboardServiceClient) GetActivityFeed(ctx context.Context, req *connect.Request[v1.GetActivityFeedRequest]) (*connect.Response[v1.GetActivityFeedResponse], error) {
	return c.getActivityFeed.CallUnary(ctx, req)
}

// DashboardServiceHandler is an implementation of the agents.v1.DashboardService service.
type DashboardServiceHandler interface {
	// GetOverview returns aggregate counts, component health and the latest
	// daemon handshake for the dashboard Overview screen.
	GetOverview(context.Context, *connect.Request[v1.GetOverviewRequest]) (*connect.Response[v1.GetOverviewResponse], error)
	// GetActivityFeed returns the most recent invocation activity, oldest event
	// first stripped, suitable for the dashboard Activity Feed widget.
	GetActivityFeed(context.Context, *connect.Request[v1.GetActivityFeedRequest]) (*connect.Response[v1.GetActivityFeedResponse], error)
}

// NewDashboardServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDashboardServiceHandler(svc DashboardServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dashboardServiceMethods := v1.File_agents_v1_dashboard_proto.Services().ByName("DashboardService").Methods()
	dashboardServiceGetOverviewHandler := connect.NewUnaryHandler(
		DashboardServiceGetOverviewProcedure,
		svc.GetOverview,
		connect.WithSchema(dashboardServiceMethods.ByName("GetOverview")),
		connect.WithHandlerOptions(opts...),
	)
	dashboardServiceGetActivityFeedHandler := connect.NewUnaryHandler(
		DashboardServiceGetActivityFeedProcedure,
		svc.GetActivityFeed,
		connect.WithSchema(dashboardServiceMethods.ByName("GetActivityFeed")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agents.v1.DashboardService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DashboardServiceGetOverviewProcedure:
			dashboardServiceGetOverviewHandler.ServeHTTP(w, r)
		case DashboardServiceGetActivityFeedProcedure:
			dashboardServiceGetActivityFeedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDashboardServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDashboardServiceHandler struct{}

func (UnimplementedDashboardServiceHandler) GetOverview(context.Context, *connect.Request[v1.GetOverviewRequest]) (*connect.Response[v1.GetOverviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.DashboardService.GetOverview is not implemented"))
}

func (UnimplementedDashboardServiceHandler) GetActivityFeed(context.Context, *connect.Request[v1.GetActivityFeedRequest]) (*connect.Response[v1.GetActivityFeedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.DashboardService.GetActivityFeed is not implemented"))
}

// DaemonServiceClient is a client for the agents.v1.DaemonService service.
type DaemonServiceClient interface {
	ListDaemons(context.Context, *connect.Request[v1.ListDaemonsRequest]) (*connect.Response[v1.ListDaemonsResponse], error)
	GetDaemon(context.Context, *connect.Request[v1.GetDaemonRequest]) (*connect.Response[v1.GetDaemonResponse], error)
	// CancelDaemonTask requests cancellation of a running task on any connected
	// daemon. Returns NotFound if no online daemon is tracking the task.
	CancelDaemonTask(context.Context, *connect.Request[v1.CancelDaemonTaskRequest]) (*connect.Response[v1.CancelDaemonTaskResponse], error)
}

// NewDaemonServiceClient constructs a client for the agents.v1.DaemonService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDaemonServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DaemonServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	daemonServiceMethods := v1.File_agents_v1_dashboard_proto.Services().ByName("DaemonService").Methods()
	return &daemonServiceClient{
		listDaemons: connect.NewClient[v1.ListDaemonsRequest, v1.ListDaemonsResponse](
			httpClient,
			baseURL+DaemonServiceListDaemonsProcedure,
			connect.WithSchema(daemonServiceMethods.ByName("ListDaemons")),
			connect.WithClientOptions(opts...),
		),
		getDaemon: connect.NewClient[v1.GetDaemonRequest, v1.GetDaemonResponse](
			httpClient,
			baseURL+DaemonServiceGetDaemonProcedure,
			connect.WithSchema(daemonServiceMethods.ByName("GetDaemon")),
			connect.WithClientOptions(opts...),
		),
		cancelDaemonTask: connect.NewClient[v1.CancelDaemonTaskRequest, v1.CancelDaemonTaskResponse](
			httpClient,
			baseURL+DaemonServiceCancelDaemonTaskProcedure,
			connect.WithSchema(daemonServiceMethods.ByName("CancelDaemonTask")),
			connect.WithClientOptions(opts...),
		),
	}
}

// daemonServiceClient implements DaemonServiceClient.
type daemonServiceClient struct {
	listDaemons      *connect.Client[v1.ListDaemonsRequest, v1.ListDaemonsResponse]
	getDaemon        *connect.Client[v1.GetDaemonRequest, v1.GetDaemonResponse]
	cancelDaemonTask *connect.Client[v1.CancelDaemonTaskRequest, v1.CancelDaemonTaskResponse]
}

// ListDaemons calls agents.v1.DaemonService.ListDaemons.
func (c *daemonServiceClient) ListDaemons(ctx context.Context, req *connect.Request[v1.ListDaemonsRequest]) (*connect.Response[v1.ListDaemonsResponse], error) {
	return c.listDaemons.CallUnary(ctx, req)
}

// GetDaemon calls agents.v1.DaemonService.GetDaemon.
func (c *daemonServiceClient) GetDaemon(ctx context.Context, req *connect.Request[v1.GetDaemonRequest]) (*connect.Response[v1.GetDaemonResponse], error) {
	return c.getDaemon.CallUnary(ctx, req)
}

// CancelDaemonTask calls agents.v1.DaemonService.CancelDaemonTask.
func (c *daemonServiceClient) CancelDaemonTask(ctx context.Context, req *connect.Request[v1.CancelDaemonTaskRequest]) (*connect.Response[v1.CancelDaemonTaskResponse], error) {
	return c.cancelDaemonTask.CallUnary(ctx, req)
}

// DaemonServiceHandler is an implementation of the agents.v1.DaemonService service.
type DaemonServiceHandler interface {
	ListDaemons(context.Context, *connect.Request[v1.ListDaemonsRequest]) (*connect.Response[v1.ListDaemonsResponse], error)
	GetDaemon(context.Context, *connect.Request[v1.GetDaemonRequest]) (*connect.Response[v1.GetDaemonResponse], error)
	// CancelDaemonTask requests cancellation of a running task on any connected
	// daemon. Returns NotFound if no online daemon is tracking the task.
	CancelDaemonTask(context.Context, *connect.Request[v1.CancelDaemonTaskRequest]) (*connect.Response[v1.CancelDaemonTaskResponse], error)
}

// NewDaemonServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDaemonServiceHandler(svc DaemonServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	daemonServiceMethods := v1.File_agents_v1_dashboard_proto.Services().ByName("DaemonService").Methods()
	daemonServiceListDaemonsHandler := connect.NewUnaryHandler(
		DaemonServiceListDaemonsProcedure,
		svc.ListDaemons,
		connect.WithSchema(daemonServiceMethods.ByName("ListDaemons")),
		connect.WithHandlerOptions(opts...),
	)
	daemonServiceGetDaemonHandler := connect.NewUnaryHandler(
		DaemonServiceGetDaemonProcedure,
		svc.GetDaemon,
		connect.WithSchema(daemonServiceMethods.ByName("GetDaemon")),
		connect.WithHandlerOptions(opts...),
	)
	daemonServiceCancelDaemonTaskHandler := connect.NewUnaryHandler(
		DaemonServiceCancelDaemonTaskProcedure,
		svc.CancelDaemonTask,
		connect.WithSchema(daemonServiceMethods.ByName("CancelDaemonTask")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agents.v1.DaemonService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DaemonServiceListDaemonsProcedure:
			daemonServiceListDaemonsHandler.ServeHTTP(w, r)
		case DaemonServiceGetDaemonProcedure:
			daemonServiceGetDaemonHandler.ServeHTTP(w, r)
		case DaemonServiceCancelDaemonTaskProcedure:
			daemonServiceCancelDaemonTaskHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDaemonServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDaemonServiceHandler struct{}

func (UnimplementedDaemonServiceHandler) ListDaemons(context.Context, *connect.Request[v1.ListDaemonsRequest]) (*connect.Response[v1.ListDaemonsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.DaemonService.ListDaemons is not implemented"))
}

func (UnimplementedDaemonServiceHandler) GetDaemon(context.Context, *connect.Request[v1.GetDaemonRequest]) (*connect.Response[v1.GetDaemonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.DaemonService.GetDaemon is not implemented"))
}

func (UnimplementedDaemonServiceHandler) CancelDaemonTask(context.Context, *connect.Request[v1.CancelDaemonTaskRequest]) (*connect.Response[v1.CancelDaemonTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.DaemonService.CancelDaemonTask is not implemented"))
}
