// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agents/v1/forum.proto

package agentsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.orx.me/apps/butter/pkg/proto/agents/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ForumServiceName is the fully-qualified name of the ForumService service.
	ForumServiceName = "agents.v1.ForumService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ForumServiceListThreadsProcedure is the fully-qualified name of the ForumService's ListThreads
	// RPC.
	ForumServiceListThreadsProcedure = "/agents.v1.ForumService/ListThreads"
	// ForumServiceGetThreadProcedure is the fully-qualified name of the ForumService's GetThread RPC.
	ForumServiceGetThreadProcedure = "/agents.v1.ForumService/GetThread"
	// ForumServiceCreateThreadProcedure is the fully-qualified name of the ForumService's CreateThread
	// RPC.
	ForumServiceCreateThreadProcedure = "/agents.v1.ForumService/CreateThread"
	// ForumServiceUpdateThreadProcedure is the fully-qualified name of the ForumService's UpdateThread
	// RPC.
	ForumServiceUpdateThreadProcedure = "/agents.v1.ForumService/UpdateThread"
	// ForumServiceDeleteThreadProcedure is the fully-qualified name of the ForumService's DeleteThread
	// RPC.
	ForumServiceDeleteThreadProcedure = "/agents.v1.ForumService/DeleteThread"
	// ForumServiceCreatePostProcedure is the fully-qualified name of the ForumService's CreatePost RPC.
	ForumServiceCreatePostProcedure = "/agents.v1.ForumService/CreatePost"
	// ForumServiceDeletePostProcedure is the fully-qualified name of the ForumService's DeletePost RPC.
	ForumServiceDeletePostProcedure = "/agents.v1.ForumService/DeletePost"
	// ForumServiceInvokeAgentInThreadProcedure is the fully-qualified name of the ForumService's
	// InvokeAgentInThread RPC.
	ForumServiceInvokeAgentInThreadProcedure = "/agents.v1.ForumService/InvokeAgentInThread"
)

// ForumServiceClient is a client for the agents.v1.ForumService service.
type ForumServiceClient interface {
	ListThreads(context.Context, *connect.Request[v1.ListForumThreadsRequest]) (*connect.Response[v1.ListForumThreadsResponse], error)
	GetThread(context.Context, *connect.Request[v1.GetForumThreadRequest]) (*connect.Response[v1.GetForumThreadResponse], error)
	CreateThread(context.Context, *connect.Request[v1.CreateForumThreadRequest]) (*connect.Response[v1.CreateForumThreadResponse], error)
	UpdateThread(context.Context, *connect.Request[v1.UpdateForumThreadRequest]) (*connect.Response[v1.UpdateForumThreadResponse], error)
	DeleteThread(context.Context, *connect.Request[v1.DeleteForumThreadRequest]) (*connect.Response[v1.DeleteForumThreadResponse], error)
	CreatePost(context.Context, *connect.Request[v1.CreateForumPostRequest]) (*connect.Response[v1.CreateForumPostResponse], error)
	DeletePost(context.Context, *connect.Request[v1.DeleteForumPostRequest]) (*connect.Response[v1.DeleteForumPostResponse], error)
	InvokeAgentInThread(context.Context, *connect.Request[v1.InvokeAgentInThreadRequest]) (*connect.Response[v1.InvokeAgentInThreadResponse], error)
}

// NewForumServiceClient constructs a client for the agents.v1.ForumService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewForumServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ForumServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	forumServiceMethods := v1.File_agents_v1_forum_proto.Services().ByName("ForumService").Methods()
	return &forumServiceClient{
		listThreads: connect.NewClient[v1.ListForumThreadsRequest, v1.ListForumThreadsResponse](
			httpClient,
			baseURL+ForumServiceListThreadsProcedure,
			connect.WithSchema(forumServiceMethods.ByName("ListThreads")),
			connect.WithClientOptions(opts...),
		),
		getThread: connect.NewClient[v1.GetForumThreadRequest, v1.GetForumThreadResponse](
			httpClient,
			baseURL+ForumServiceGetThreadProcedure,
			connect.WithSchema(forumServiceMethods.ByName("GetThread")),
			connect.WithClientOptions(opts...),
		),
		createThread: connect.NewClient[v1.CreateForumThreadRequest, v1.CreateForumThreadResponse](
			httpClient,
			baseURL+ForumServiceCreateThreadProcedure,
			connect.WithSchema(forumServiceMethods.ByName("CreateThread")),
			connect.WithClientOptions(opts...),
		),
		updateThread: connect.NewClient[v1.UpdateForumThreadRequest, v1.UpdateForumThreadResponse](
			httpClient,
			baseURL+ForumServiceUpdateThreadProcedure,
			connect.WithSchema(forumServiceMethods.ByName("UpdateThread")),
			connect.WithClientOptions(opts...),
		),
		deleteThread: connect.NewClient[v1.DeleteForumThreadRequest, v1.DeleteForumThreadResponse](
			httpClient,
			baseURL+ForumServiceDeleteThreadProcedure,
			connect.WithSchema(forumServiceMethods.ByName("DeleteThread")),
			connect.WithClientOptions(opts...),
		),
		createPost: connect.NewClient[v1.CreateForumPostRequest, v1.CreateForumPostResponse](
			httpClient,
			baseURL+ForumServiceCreatePostProcedure,
			connect.WithSchema(forumServiceMethods.ByName("CreatePost")),
			connect.WithClientOptions(opts...),
		),
		deletePost: connect.NewClient[v1.DeleteForumPostRequest, v1.DeleteForumPostResponse](
			httpClient,
			baseURL+ForumServiceDeletePostProcedure,
			connect.WithSchema(forumServiceMethods.ByName("DeletePost")),
			connect.WithClientOptions(opts...),
		),
		invokeAgentInThread: connect.NewClient[v1.InvokeAgentInThreadRequest, v1.InvokeAgentInThreadResponse](
			httpClient,
			baseURL+ForumServiceInvokeAgentInThreadProcedure,
			connect.WithSchema(forumServiceMethods.ByName("InvokeAgentInThread")),
			connect.WithClientOptions(opts...),
		),
	}
}

// forumServiceClient implements ForumServiceClient.
type forumServiceClient struct {
	listThreads         *connect.Client[v1.ListForumThreadsRequest, v1.ListForumThreadsResponse]
	getThread           *connect.Client[v1.GetForumThreadRequest, v1.GetForumThreadResponse]
	createThread        *connect.Client[v1.CreateForumThreadRequest, v1.CreateForumThreadResponse]
	updateThread        *connect.Client[v1.UpdateForumThreadRequest, v1.UpdateForumThreadResponse]
	deleteThread        *connect.Client[v1.DeleteForumThreadRequest, v1.DeleteForumThreadResponse]
	createPost          *connect.Client[v1.CreateForumPostRequest, v1.CreateForumPostResponse]
	deletePost          *connect.Client[v1.DeleteForumPostRequest, v1.DeleteForumPostResponse]
	invokeAgentInThread *connect.Client[v1.InvokeAgentInThreadRequest, v1.InvokeAgentInThreadResponse]
}

// ListThreads calls agents.v1.ForumService.ListThreads.
func (c *forumServiceClient) ListThreads(ctx context.Context, req *connect.Request[v1.ListForumThreadsRequest]) (*connect.Response[v1.ListForumThreadsResponse], error) {
	return c.listThreads.CallUnary(ctx, req)
}

// GetThread calls agents.v1.ForumService.GetThread.
func (c *forumServiceClient) GetThread(ctx context.Context, req *connect.Request[v1.GetForumThreadRequest]) (*connect.Response[v1.GetForumThreadResponse], error) {
	return c.getThread.CallUnary(ctx, req)
}

// CreateThread calls agents.v1.ForumService.CreateThread.
func (c *forumServiceClient) CreateThread(ctx context.Context, req *connect.Request[v1.CreateForumThreadRequest]) (*connect.Response[v1.CreateForumThreadResponse], error) {
	return c.createThread.CallUnary(ctx, req)
}

// UpdateThread calls agents.v1.ForumService.UpdateThread.
func (c *forumServiceClient) UpdateThread(ctx context.Context, req *connect.Request[v1.UpdateForumThreadRequest]) (*connect.Response[v1.UpdateForumThreadResponse], error) {
	return c.updateThread.CallUnary(ctx, req)
}

// DeleteThread calls agents.v1.ForumService.DeleteThread.
func (c *forumServiceClient) DeleteThread(ctx context.Context, req *connect.Request[v1.DeleteForumThreadRequest]) (*connect.Response[v1.DeleteForumThreadResponse], error) {
	return c.deleteThread.CallUnary(ctx, req)
}

// CreatePost calls agents.v1.ForumService.CreatePost.
func (c *forumServiceClient) CreatePost(ctx context.Context, req *connect.Request[v1.CreateForumPostRequest]) (*connect.Response[v1.CreateForumPostResponse], error) {
	return c.createPost.CallUnary(ctx, req)
}

// DeletePost calls agents.v1.ForumService.DeletePost.
func (c *forumServiceClient) DeletePost(ctx context.Context, req *connect.Request[v1.DeleteForumPostRequest]) (*connect.Response[v1.DeleteForumPostResponse], error) {
	return c.deletePost.CallUnary(ctx, req)
}

// InvokeAgentInThread calls agents.v1.ForumService.InvokeAgentInThread.
func (c *forumServiceClient) InvokeAgentInThread(ctx context.Context, req *connect.Request[v1.InvokeAgentInThreadRequest]) (*connect.Response[v1.InvokeAgentInThreadResponse], error) {
	return c.invokeAgentInThread.CallUnary(ctx, req)
}

// ForumServiceHandler is an implementation of the agents.v1.ForumService service.
type ForumServiceHandler interface {
	ListThreads(context.Context, *connect.Request[v1.ListForumThreadsRequest]) (*connect.Response[v1.ListForumThreadsResponse], error)
	GetThread(context.Context, *connect.Request[v1.GetForumThreadRequest]) (*connect.Response[v1.GetForumThreadResponse], error)
	CreateThread(context.Context, *connect.Request[v1.CreateForumThreadRequest]) (*connect.Response[v1.CreateForumThreadResponse], error)
	UpdateThread(context.Context, *connect.Request[v1.UpdateForumThreadRequest]) (*connect.Response[v1.UpdateForumThreadResponse], error)
	DeleteThread(context.Context, *connect.Request[v1.DeleteForumThreadRequest]) (*connect.Response[v1.DeleteForumThreadResponse], error)
	CreatePost(context.Context, *connect.Request[v1.CreateForumPostRequest]) (*connect.Response[v1.CreateForumPostResponse], error)
	DeletePost(context.Context, *connect.Request[v1.DeleteForumPostRequest]) (*connect.Response[v1.DeleteForumPostResponse], error)
	InvokeAgentInThread(context.Context, *connect.Request[v1.InvokeAgentInThreadRequest]) (*connect.Response[v1.InvokeAgentInThreadResponse], error)
}

// NewForumServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewForumServiceHandler(svc ForumServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	forumServiceMethods := v1.File_agents_v1_forum_proto.Services().ByName("ForumService").Methods()
	forumServiceListThreadsHandler := connect.NewUnaryHandler(
		ForumServiceListThreadsProcedure,
		svc.ListThreads,
		connect.WithSchema(forumServiceMethods.ByName("ListThreads")),
		connect.WithHandlerOptions(opts...),
	)
	forumServiceGetThreadHandler := connect.NewUnaryHandler(
		ForumServiceGetThreadProcedure,
		svc.GetThread,
		connect.WithSchema(forumServiceMethods.ByName("GetThread")),
		connect.WithHandlerOptions(opts...),
	)
	forumServiceCreateThreadHandler := connect.NewUnaryHandler(
		ForumServiceCreateThreadProcedure,
		svc.CreateThread,
		connect.WithSchema(forumServiceMethods.ByName("CreateThread")),
		connect.WithHandlerOptions(opts...),
	)
	forumServiceUpdateThreadHandler := connect.NewUnaryHandler(
		ForumServiceUpdateThreadProcedure,
		svc.UpdateThread,
		connect.WithSchema(forumServiceMethods.ByName("UpdateThread")),
		connect.WithHandlerOptions(opts...),
	)
	forumServiceDeleteThreadHandler := connect.NewUnaryHandler(
		ForumServiceDeleteThreadProcedure,
		svc.DeleteThread,
		connect.WithSchema(forumServiceMethods.ByName("DeleteThread")),
		connect.WithHandlerOptions(opts...),
	)
	forumServiceCreatePostHandler := connect.NewUnaryHandler(
		ForumServiceCreatePostProcedure,
		svc.CreatePost,
		connect.WithSchema(forumServiceMethods.ByName("CreatePost")),
		connect.WithHandlerOptions(opts...),
	)
	forumServiceDeletePostHandler := connect.NewUnaryHandler(
		ForumServiceDeletePostProcedure,
		svc.DeletePost,
		connect.WithSchema(forumServiceMethods.ByName("DeletePost")),
		connect.WithHandlerOptions(opts...),
	)
	forumServiceInvokeAgentInThreadHandler := connect.NewUnaryHandler(
		ForumServiceInvokeAgentInThreadProcedure,
		svc.InvokeAgentInThread,
		connect.WithSchema(forumServiceMethods.ByName("InvokeAgentInThread")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agents.v1.ForumService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ForumServiceListThreadsProcedure:
			forumServiceListThreadsHandler.ServeHTTP(w, r)
		case ForumServiceGetThreadProcedure:
			forumServiceGetThreadHandler.ServeHTTP(w, r)
		case ForumServiceCreateThreadProcedure:
			forumServiceCreateThreadHandler.ServeHTTP(w, r)
		case ForumServiceUpdateThreadProcedure:
			forumServiceUpdateThreadHandler.ServeHTTP(w, r)
		case ForumServiceDeleteThreadProcedure:
			forumServiceDeleteThreadHandler.ServeHTTP(w, r)
		case ForumServiceCreatePostProcedure:
			forumServiceCreatePostHandler.ServeHTTP(w, r)
		case ForumServiceDeletePostProcedure:
			forumServiceDeletePostHandler.ServeHTTP(w, r)
		case ForumServiceInvokeAgentInThreadProcedure:
			forumServiceInvokeAgentInThreadHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedForumServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedForumServiceHandler struct{}

func (UnimplementedForumServiceHandler) ListThreads(context.Context, *connect.Request[v1.ListForumThreadsRequest]) (*connect.Response[v1.ListForumThreadsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.ForumService.ListThreads is not implemented"))
}

func (UnimplementedForumServiceHandler) GetThread(context.Context, *connect.Request[v1.GetForumThreadRequest]) (*connect.Response[v1.GetForumThreadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.ForumService.GetThread is not implemented"))
}

func (UnimplementedForumServiceHandler) CreateThread(context.Context, *connect.Request[v1.CreateForumThreadRequest]) (*connect.Response[v1.CreateForumThreadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.ForumService.CreateThread is not implemented"))
}

func (UnimplementedForumServiceHandler) UpdateThread(context.Context, *connect.Request[v1.UpdateForumThreadRequest]) (*connect.Response[v1.UpdateForumThreadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.ForumService.UpdateThread is not implemented"))
}

func (UnimplementedForumServiceHandler) DeleteThread(context.Context, *connect.Request[v1.DeleteForumThreadRequest]) (*connect.Response[v1.DeleteForumThreadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.ForumService.DeleteThread is not implemented"))
}

func (UnimplementedForumServiceHandler) CreatePost(context.Context, *connect.Request[v1.CreateForumPostRequest]) (*connect.Response[v1.CreateForumPostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.ForumService.CreatePost is not implemented"))
}

func (UnimplementedForumServiceHandler) DeletePost(context.Context, *connect.Request[v1.DeleteForumPostRequest]) (*connect.Response[v1.DeleteForumPostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.ForumService.DeletePost is not implemented"))
}

func (UnimplementedForumServiceHandler) InvokeAgentInThread(context.Context, *connect.Request[v1.InvokeAgentInThreadRequest]) (*connect.Response[v1.InvokeAgentInThreadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agents.v1.ForumService.InvokeAgentInThread is not implemented"))
}
