// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: agents/v1/butterbox.proto

package agentsv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ButterBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Stable server-assigned identifier (UUID).
	// @gotags: json:"id,omitempty" yaml:"id,omitempty" bson:"_id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id,omitempty" bson:"_id,omitempty"`
	// Human-readable name, unique within the workspace.
	// @gotags: json:"name,omitempty" yaml:"name,omitempty" bson:"name,omitempty"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" yaml:"name,omitempty" bson:"name,omitempty"`
	// Base URL the box's HTTP server listens on, e.g. "https://box.example.com".
	// PiService lives under it at /butterbox.pi.v1.PiService/; pi-web (when
	// enabled on the box) is served at its root.
	// @gotags: json:"base_url,omitempty" yaml:"base_url,omitempty" bson:"base_url,omitempty"
	BaseUrl string `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty" yaml:"base_url,omitempty" bson:"base_url,omitempty"`
	// When false the box is not offered for new Pi agent bindings.
	// @gotags: json:"enabled,omitempty" yaml:"enabled,omitempty" bson:"enabled,omitempty"
	Enabled bool `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty" yaml:"enabled,omitempty" bson:"enabled,omitempty"`
	// Reports whether an access token is stored for this box. Derived from
	// the credential columns on every read; never taken from client input.
	// @gotags: json:"credential_set,omitempty" yaml:"credential_set,omitempty" bson:"credential_set,omitempty"
	CredentialSet bool `protobuf:"varint,5,opt,name=credential_set,json=credentialSet,proto3" json:"credential_set,omitempty" yaml:"credential_set,omitempty" bson:"credential_set,omitempty"`
	// When the access token was last set or rotated. Unset when no token is
	// stored.
	// @gotags: json:"credential_updated_at,omitempty" yaml:"credential_updated_at,omitempty" bson:"credential_updated_at,omitempty"
	CredentialUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=credential_updated_at,json=credentialUpdatedAt,proto3" json:"credential_updated_at,omitempty" yaml:"credential_updated_at,omitempty" bson:"credential_updated_at,omitempty"`
	// @gotags: json:"created_at,omitempty" yaml:"created_at,omitempty" bson:"created_at,omitempty"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" yaml:"created_at,omitempty" bson:"created_at,omitempty"`
	// @gotags: json:"updated_at,omitempty" yaml:"updated_at,omitempty" bson:"updated_at,omitempty"
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" yaml:"updated_at,omitempty" bson:"updated_at,omitempty"`
	// ID of the workspace this box belongs to. Stamped by the repository from
	// request context; never taken from client input.
	// @gotags: json:"workspace_id,omitempty" yaml:"workspace_id,omitempty" bson:"workspace_id,omitempty"
	WorkspaceId string `protobuf:"bytes,100,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty" yaml:"workspace_id,omitempty" bson:"workspace_id,omitempty"`
}

func (x *ButterBox) Reset() {
	*x = ButterBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ButterBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButterBox) ProtoMessage() {}

func (x *ButterBox) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButterBox.ProtoReflect.Descriptor instead.
func (*ButterBox) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{0}
}

func (x *ButterBox) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ButterBox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ButterBox) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ButterBox) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ButterBox) GetCredentialSet() bool {
	if x != nil {
		return x.CredentialSet
	}
	return false
}

func (x *ButterBox) GetCredentialUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CredentialUpdatedAt
	}
	return nil
}

func (x *ButterBox) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ButterBox) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ButterBox) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ListButterBoxesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListButterBoxesRequest) Reset() {
	*x = ListButterBoxesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListButterBoxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListButterBoxesRequest) ProtoMessage() {}

func (x *ListButterBoxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListButterBoxesRequest.ProtoReflect.Descriptor instead.
func (*ListButterBoxesRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{1}
}

type ListButterBoxesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ButterBoxes []*ButterBox `protobuf:"bytes,1,rep,name=butter_boxes,json=butterBoxes,proto3" json:"butter_boxes,omitempty"`
}

func (x *ListButterBoxesResponse) Reset() {
	*x = ListButterBoxesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListButterBoxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListButterBoxesResponse) ProtoMessage() {}

func (x *ListButterBoxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListButterBoxesResponse.ProtoReflect.Descriptor instead.
func (*ListButterBoxesResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{2}
}

func (x *ListButterBoxesResponse) GetButterBoxes() []*ButterBox {
	if x != nil {
		return x.ButterBoxes
	}
	return nil
}

type GetButterBoxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetButterBoxRequest) Reset() {
	*x = GetButterBoxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetButterBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetButterBoxRequest) ProtoMessage() {}

func (x *GetButterBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetButterBoxRequest.ProtoReflect.Descriptor instead.
func (*GetButterBoxRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{3}
}

func (x *GetButterBoxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetButterBoxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ButterBox *ButterBox `protobuf:"bytes,1,opt,name=butter_box,json=butterBox,proto3" json:"butter_box,omitempty"`
}

func (x *GetButterBoxResponse) Reset() {
	*x = GetButterBoxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetButterBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetButterBoxResponse) ProtoMessage() {}

func (x *GetButterBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetButterBoxResponse.ProtoReflect.Descriptor instead.
func (*GetButterBoxResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{4}
}

func (x *GetButterBoxResponse) GetButterBox() *ButterBox {
	if x != nil {
		return x.ButterBox
	}
	return nil
}

type CreateButterBoxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BaseUrl string `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Enabled bool   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Optional access token, stored through the credential seam atomically
	// with the box. Write-only.
	Token string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateButterBoxRequest) Reset() {
	*x = CreateButterBoxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateButterBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateButterBoxRequest) ProtoMessage() {}

func (x *CreateButterBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateButterBoxRequest.ProtoReflect.Descriptor instead.
func (*CreateButterBoxRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{5}
}

func (x *CreateButterBoxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateButterBoxRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CreateButterBoxRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateButterBoxRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateButterBoxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ButterBox *ButterBox `protobuf:"bytes,1,opt,name=butter_box,json=butterBox,proto3" json:"butter_box,omitempty"`
}

func (x *CreateButterBoxResponse) Reset() {
	*x = CreateButterBoxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateButterBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateButterBoxResponse) ProtoMessage() {}

func (x *CreateButterBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateButterBoxResponse.ProtoReflect.Descriptor instead.
func (*CreateButterBoxResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{6}
}

func (x *CreateButterBoxResponse) GetButterBox() *ButterBox {
	if x != nil {
		return x.ButterBox
	}
	return nil
}

type UpdateButterBoxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaseUrl string `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Enabled bool   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *UpdateButterBoxRequest) Reset() {
	*x = UpdateButterBoxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateButterBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateButterBoxRequest) ProtoMessage() {}

func (x *UpdateButterBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateButterBoxRequest.ProtoReflect.Descriptor instead.
func (*UpdateButterBoxRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateButterBoxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateButterBoxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateButterBoxRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *UpdateButterBoxRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateButterBoxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ButterBox *ButterBox `protobuf:"bytes,1,opt,name=butter_box,json=butterBox,proto3" json:"butter_box,omitempty"`
}

func (x *UpdateButterBoxResponse) Reset() {
	*x = UpdateButterBoxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateButterBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateButterBoxResponse) ProtoMessage() {}

func (x *UpdateButterBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateButterBoxResponse.ProtoReflect.Descriptor instead.
func (*UpdateButterBoxResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateButterBoxResponse) GetButterBox() *ButterBox {
	if x != nil {
		return x.ButterBox
	}
	return nil
}

type DeleteButterBoxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteButterBoxRequest) Reset() {
	*x = DeleteButterBoxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteButterBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteButterBoxRequest) ProtoMessage() {}

func (x *DeleteButterBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteButterBoxRequest.ProtoReflect.Descriptor instead.
func (*DeleteButterBoxRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteButterBoxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteButterBoxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteButterBoxResponse) Reset() {
	*x = DeleteButterBoxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteButterBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteButterBoxResponse) ProtoMessage() {}

func (x *DeleteButterBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteButterBoxResponse.ProtoReflect.Descriptor instead.
func (*DeleteButterBoxResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{10}
}

type SetButterBoxTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// New access token; empty clears the stored token.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SetButterBoxTokenRequest) Reset() {
	*x = SetButterBoxTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetButterBoxTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetButterBoxTokenRequest) ProtoMessage() {}

func (x *SetButterBoxTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetButterBoxTokenRequest.ProtoReflect.Descriptor instead.
func (*SetButterBoxTokenRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{11}
}

func (x *SetButterBoxTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetButterBoxTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SetButterBoxTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ButterBox *ButterBox `protobuf:"bytes,1,opt,name=butter_box,json=butterBox,proto3" json:"butter_box,omitempty"`
}

func (x *SetButterBoxTokenResponse) Reset() {
	*x = SetButterBoxTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetButterBoxTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetButterBoxTokenResponse) ProtoMessage() {}

func (x *SetButterBoxTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetButterBoxTokenResponse.ProtoReflect.Descriptor instead.
func (*SetButterBoxTokenResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{12}
}

func (x *SetButterBoxTokenResponse) GetButterBox() *ButterBox {
	if x != nil {
		return x.ButterBox
	}
	return nil
}

type GetButterBoxStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetButterBoxStatusRequest) Reset() {
	*x = GetButterBoxStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetButterBoxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetButterBoxStatusRequest) ProtoMessage() {}

func (x *GetButterBoxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetButterBoxStatusRequest.ProtoReflect.Descriptor instead.
func (*GetButterBoxStatusRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{13}
}

func (x *GetButterBoxStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetButterBoxStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// True when the box answered the probe.
	Reachable bool `protobuf:"varint,1,opt,name=reachable,proto3" json:"reachable,omitempty"`
	// Number of active pi sessions on the box. Zero when unreachable.
	ActiveSessions int32 `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	// Human-readable probe failure, empty when reachable.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetButterBoxStatusResponse) Reset() {
	*x = GetButterBoxStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetButterBoxStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetButterBoxStatusResponse) ProtoMessage() {}

func (x *GetButterBoxStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetButterBoxStatusResponse.ProtoReflect.Descriptor instead.
func (*GetButterBoxStatusResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{14}
}

func (x *GetButterBoxStatusResponse) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *GetButterBoxStatusResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *GetButterBoxStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListButterBoxModelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListButterBoxModelsRequest) Reset() {
	*x = ListButterBoxModelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListButterBoxModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListButterBoxModelsRequest) ProtoMessage() {}

func (x *ListButterBoxModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListButterBoxModelsRequest.ProtoReflect.Descriptor instead.
func (*ListButterBoxModelsRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{15}
}

func (x *ListButterBoxModelsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListButterBoxModelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Models []*ButterBoxModel `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
}

func (x *ListButterBoxModelsResponse) Reset() {
	*x = ListButterBoxModelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListButterBoxModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListButterBoxModelsResponse) ProtoMessage() {}

func (x *ListButterBoxModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListButterBoxModelsResponse.ProtoReflect.Descriptor instead.
func (*ListButterBoxModelsResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{16}
}

func (x *ListButterBoxModelsResponse) GetModels() []*ButterBoxModel {
	if x != nil {
		return x.Models
	}
	return nil
}

// ButterBoxModel is one entry of a box's pi model catalog, trimmed to what
// agent configuration needs.
type ButterBoxModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Model ID as accepted by pi (e.g. "claude-fable-5").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Provider ID (e.g. "anthropic").
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// Human-readable model name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// True when the model supports reasoning/thinking levels.
	Reasoning bool `protobuf:"varint,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
}

func (x *ButterBoxModel) Reset() {
	*x = ButterBoxModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ButterBoxModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButterBoxModel) ProtoMessage() {}

func (x *ButterBoxModel) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButterBoxModel.ProtoReflect.Descriptor instead.
func (*ButterBoxModel) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{17}
}

func (x *ButterBoxModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ButterBoxModel) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ButterBoxModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ButterBoxModel) GetReasoning() bool {
	if x != nil {
		return x.Reasoning
	}
	return false
}

type ListCursorModelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListCursorModelsRequest) Reset() {
	*x = ListCursorModelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCursorModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCursorModelsRequest) ProtoMessage() {}

func (x *ListCursorModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCursorModelsRequest.ProtoReflect.Descriptor instead.
func (*ListCursorModelsRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{18}
}

func (x *ListCursorModelsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCursorModelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Models []*CursorBoxModel `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
}

func (x *ListCursorModelsResponse) Reset() {
	*x = ListCursorModelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCursorModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCursorModelsResponse) ProtoMessage() {}

func (x *ListCursorModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCursorModelsResponse.ProtoReflect.Descriptor instead.
func (*ListCursorModelsResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{19}
}

func (x *ListCursorModelsResponse) GetModels() []*CursorBoxModel {
	if x != nil {
		return x.Models
	}
	return nil
}

// CursorBoxModel is one entry of a box's Cursor model catalog, trimmed to
// what agent configuration needs.
type CursorBoxModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Cursor model ID (e.g. "composer-2.5"), usable as
	// CursorAgentConfig.model.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable model name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CursorBoxModel) Reset() {
	*x = CursorBoxModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_butterbox_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CursorBoxModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorBoxModel) ProtoMessage() {}

func (x *CursorBoxModel) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_butterbox_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorBoxModel.ProtoReflect.Descriptor instead.
func (*CursorBoxModel) Descriptor() ([]byte, []int) {
	return file_agents_v1_butterbox_proto_rawDescGZIP(), []int{20}
}

func (x *CursorBoxModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CursorBoxModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_agents_v1_butterbox_proto protoreflect.FileDescriptor

var file_agents_v1_butterbox_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x75, 0x74, 0x74,
	0x65, 0x72, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x86, 0x03, 0x0a, 0x09, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x08, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x74,
	0x12, 0x4e, 0x0a, 0x15, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x13, 0x63, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x52, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65,
	0x72, 0x42, 0x6f, 0x78, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37,
	0x0a, 0x0c, 0x62, 0x75, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x0b, 0x62, 0x75, 0x74, 0x74,
	0x65, 0x72, 0x42, 0x6f, 0x78, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x75,
	0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72,
	0x02, 0x10, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x75,
	0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x0a, 0x62, 0x75, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x09, 0x62, 0x75, 0x74, 0x74, 0x65,
	0x72, 0x42, 0x6f, 0x78, 0x22, 0x89, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x08,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x4e, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72,
	0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x62,
	0x75, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x74, 0x74,
	0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x09, 0x62, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78,
	0x22, 0x8c, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74, 0x65,
	0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x22, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x62, 0x61,
	0x73, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22,
	0x4e, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42,
	0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x62, 0x75,
	0x74, 0x74, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x74, 0x74, 0x65,
	0x72, 0x42, 0x6f, 0x78, 0x52, 0x09, 0x62, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x22,
	0x31, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42,
	0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74,
	0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x49, 0x0a,
	0x18, 0x53, 0x65, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x50, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x42,
	0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x62, 0x75, 0x74, 0x74, 0x65, 0x72, 0x5f,
	0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52,
	0x09, 0x62, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x22, 0x34, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x79, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x0f,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x1a, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x50, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72,
	0x42, 0x6f, 0x78, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x31, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75,
	0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x06, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x22, 0x6e, 0x0a, 0x0e, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f,
	0x78, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x69, 0x6e, 0x67, 0x22, 0x32, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x10, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x42, 0x6f, 0x78, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52,
	0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x34, 0x0a, 0x0e, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x42, 0x6f, 0x78, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xd1, 0x06,
	0x0a, 0x10, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72,
	0x42, 0x6f, 0x78, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42,
	0x6f, 0x78, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x12, 0x1e, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x74, 0x74,
	0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x74, 0x74,
	0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78,
	0x12, 0x21, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x12, 0x21, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x74,
	0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x58, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74, 0x65,
	0x72, 0x42, 0x6f, 0x78, 0x12, 0x21, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72,
	0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x11, 0x53,
	0x65, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x23, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74,
	0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x24, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x25, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x74,
	0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x22, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x6f, 0x2e, 0x6f, 0x72, 0x78, 0x2e, 0x6d, 0x65, 0x2f, 0x61,
	0x70, 0x70, 0x73, 0x2f, 0x62, 0x75, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agents_v1_butterbox_proto_rawDescOnce sync.Once
	file_agents_v1_butterbox_proto_rawDescData = file_agents_v1_butterbox_proto_rawDesc
)

func file_agents_v1_butterbox_proto_rawDescGZIP() []byte {
	file_agents_v1_butterbox_proto_rawDescOnce.Do(func() {
		file_agents_v1_butterbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_agents_v1_butterbox_proto_rawDescData)
	})
	return file_agents_v1_butterbox_proto_rawDescData
}

var file_agents_v1_butterbox_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_agents_v1_butterbox_proto_goTypes = []interface{}{
	(*ButterBox)(nil),                   // 0: agents.v1.ButterBox
	(*ListButterBoxesRequest)(nil),      // 1: agents.v1.ListButterBoxesRequest
	(*ListButterBoxesResponse)(nil),     // 2: agents.v1.ListButterBoxesResponse
	(*GetButterBoxRequest)(nil),         // 3: agents.v1.GetButterBoxRequest
	(*GetButterBoxResponse)(nil),        // 4: agents.v1.GetButterBoxResponse
	(*CreateButterBoxRequest)(nil),      // 5: agents.v1.CreateButterBoxRequest
	(*CreateButterBoxResponse)(nil),     // 6: agents.v1.CreateButterBoxResponse
	(*UpdateButterBoxRequest)(nil),      // 7: agents.v1.UpdateButterBoxRequest
	(*UpdateButterBoxResponse)(nil),     // 8: agents.v1.UpdateButterBoxResponse
	(*DeleteButterBoxRequest)(nil),      // 9: agents.v1.DeleteButterBoxRequest
	(*DeleteButterBoxResponse)(nil),     // 10: agents.v1.DeleteButterBoxResponse
	(*SetButterBoxTokenRequest)(nil),    // 11: agents.v1.SetButterBoxTokenRequest
	(*SetButterBoxTokenResponse)(nil),   // 12: agents.v1.SetButterBoxTokenResponse
	(*GetButterBoxStatusRequest)(nil),   // 13: agents.v1.GetButterBoxStatusRequest
	(*GetButterBoxStatusResponse)(nil),  // 14: agents.v1.GetButterBoxStatusResponse
	(*ListButterBoxModelsRequest)(nil),  // 15: agents.v1.ListButterBoxModelsRequest
	(*ListButterBoxModelsResponse)(nil), // 16: agents.v1.ListButterBoxModelsResponse
	(*ButterBoxModel)(nil),              // 17: agents.v1.ButterBoxModel
	(*ListCursorModelsRequest)(nil),     // 18: agents.v1.ListCursorModelsRequest
	(*ListCursorModelsResponse)(nil),    // 19: agents.v1.ListCursorModelsResponse
	(*CursorBoxModel)(nil),              // 20: agents.v1.CursorBoxModel
	(*timestamppb.Timestamp)(nil),       // 21: google.protobuf.Timestamp
}
var file_agents_v1_butterbox_proto_depIdxs = []int32{
	21, // 0: agents.v1.ButterBox.credential_updated_at:type_name -> google.protobuf.Timestamp
	21, // 1: agents.v1.ButterBox.created_at:type_name -> google.protobuf.Timestamp
	21, // 2: agents.v1.ButterBox.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: agents.v1.ListButterBoxesResponse.butter_boxes:type_name -> agents.v1.ButterBox
	0,  // 4: agents.v1.GetButterBoxResponse.butter_box:type_name -> agents.v1.ButterBox
	0,  // 5: agents.v1.CreateButterBoxResponse.butter_box:type_name -> agents.v1.ButterBox
	0,  // 6: agents.v1.UpdateButterBoxResponse.butter_box:type_name -> agents.v1.ButterBox
	0,  // 7: agents.v1.SetButterBoxTokenResponse.butter_box:type_name -> agents.v1.ButterBox
	17, // 8: agents.v1.ListButterBoxModelsResponse.models:type_name -> agents.v1.ButterBoxModel
	20, // 9: agents.v1.ListCursorModelsResponse.models:type_name -> agents.v1.CursorBoxModel
	1,  // 10: agents.v1.ButterBoxService.ListButterBoxes:input_type -> agents.v1.ListButterBoxesRequest
	3,  // 11: agents.v1.ButterBoxService.GetButterBox:input_type -> agents.v1.GetButterBoxRequest
	5,  // 12: agents.v1.ButterBoxService.CreateButterBox:input_type -> agents.v1.CreateButterBoxRequest
	7,  // 13: agents.v1.ButterBoxService.UpdateButterBox:input_type -> agents.v1.UpdateButterBoxRequest
	9,  // 14: agents.v1.ButterBoxService.DeleteButterBox:input_type -> agents.v1.DeleteButterBoxRequest
	11, // 15: agents.v1.ButterBoxService.SetButterBoxToken:input_type -> agents.v1.SetButterBoxTokenRequest
	13, // 16: agents.v1.ButterBoxService.GetButterBoxStatus:input_type -> agents.v1.GetButterBoxStatusRequest
	15, // 17: agents.v1.ButterBoxService.ListButterBoxModels:input_type -> agents.v1.ListButterBoxModelsRequest
	18, // 18: agents.v1.ButterBoxService.ListCursorModels:input_type -> agents.v1.ListCursorModelsRequest
	2,  // 19: agents.v1.ButterBoxService.ListButterBoxes:output_type -> agents.v1.ListButterBoxesResponse
	4,  // 20: agents.v1.ButterBoxService.GetButterBox:output_type -> agents.v1.GetButterBoxResponse
	6,  // 21: agents.v1.ButterBoxService.CreateButterBox:output_type -> agents.v1.CreateButterBoxResponse
	8,  // 22: agents.v1.ButterBoxService.UpdateButterBox:output_type -> agents.v1.UpdateButterBoxResponse
	10, // 23: agents.v1.ButterBoxService.DeleteButterBox:output_type -> agents.v1.DeleteButterBoxResponse
	12, // 24: agents.v1.ButterBoxService.SetButterBoxToken:output_type -> agents.v1.SetButterBoxTokenResponse
	14, // 25: agents.v1.ButterBoxService.GetButterBoxStatus:output_type -> agents.v1.GetButterBoxStatusResponse
	16, // 26: agents.v1.ButterBoxService.ListButterBoxModels:output_type -> agents.v1.ListButterBoxModelsResponse
	19, // 27: agents.v1.ButterBoxService.ListCursorModels:output_type -> agents.v1.ListCursorModelsResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_agents_v1_butterbox_proto_init() }
func file_agents_v1_butterbox_proto_init() {
	if File_agents_v1_butterbox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agents_v1_butterbox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ButterBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListButterBoxesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListButterBoxesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetButterBoxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetButterBoxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateButterBoxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateButterBoxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateButterBoxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateButterBoxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteButterBoxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteButterBoxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetButterBoxTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetButterBoxTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetButterBoxStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetButterBoxStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListButterBoxModelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListButterBoxModelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ButterBoxModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCursorModelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCursorModelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_butterbox_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CursorBoxModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agents_v1_butterbox_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agents_v1_butterbox_proto_goTypes,
		DependencyIndexes: file_agents_v1_butterbox_proto_depIdxs,
		MessageInfos:      file_agents_v1_butterbox_proto_msgTypes,
	}.Build()
	File_agents_v1_butterbox_proto = out.File
	file_agents_v1_butterbox_proto_rawDesc = nil
	file_agents_v1_butterbox_proto_goTypes = nil
	file_agents_v1_butterbox_proto_depIdxs = nil
}
