// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: agents/v1/cron.proto

package agentsv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CronJob with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CronJob) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CronJob with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CronJobMultiError, or nil if none found.
func (m *CronJob) ValidateAll() error {
	return m.validate(true)
}

func (m *CronJob) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CronJobValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSchedule()) < 1 {
		err := CronJobValidationError{
			field:  "Schedule",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAgentName()) < 1 {
		err := CronJobValidationError{
			field:  "AgentName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Input

	// no validation rules for Timezone

	// no validation rules for Enabled

	if all {
		switch v := interface{}(m.GetDelivery()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CronJobValidationError{
					field:  "Delivery",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CronJobValidationError{
					field:  "Delivery",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDelivery()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CronJobValidationError{
				field:  "Delivery",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Metadata

	// no validation rules for WorkspaceId

	if len(errors) > 0 {
		return CronJobMultiError(errors)
	}

	return nil
}

// CronJobMultiError is an error wrapping multiple validation errors returned
// by CronJob.ValidateAll() if the designated constraints aren't met.
type CronJobMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CronJobMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CronJobMultiError) AllErrors() []error { return m }

// CronJobValidationError is the validation error returned by CronJob.Validate
// if the designated constraints aren't met.
type CronJobValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CronJobValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CronJobValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CronJobValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CronJobValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CronJobValidationError) ErrorName() string { return "CronJobValidationError" }

// Error satisfies the builtin error interface
func (e CronJobValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCronJob.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CronJobValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CronJobValidationError{}

// Validate checks the field values on CronDelivery with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CronDelivery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CronDelivery with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CronDeliveryMultiError, or
// nil if none found.
func (m *CronDelivery) ValidateAll() error {
	return m.validate(true)
}

func (m *CronDelivery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for WebhookUrl

	// no validation rules for ChannelName

	// no validation rules for ChatId

	if len(errors) > 0 {
		return CronDeliveryMultiError(errors)
	}

	return nil
}

// CronDeliveryMultiError is an error wrapping multiple validation errors
// returned by CronDelivery.ValidateAll() if the designated constraints aren't met.
type CronDeliveryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CronDeliveryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CronDeliveryMultiError) AllErrors() []error { return m }

// CronDeliveryValidationError is the validation error returned by
// CronDelivery.Validate if the designated constraints aren't met.
type CronDeliveryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CronDeliveryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CronDeliveryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CronDeliveryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CronDeliveryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CronDeliveryValidationError) ErrorName() string { return "CronDeliveryValidationError" }

// Error satisfies the builtin error interface
func (e CronDeliveryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCronDelivery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CronDeliveryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CronDeliveryValidationError{}

// Validate checks the field values on CronExecution with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CronExecution) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CronExecution with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CronExecutionMultiError, or
// nil if none found.
func (m *CronExecution) ValidateAll() error {
	return m.validate(true)
}

func (m *CronExecution) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for JobName

	// no validation rules for AgentName

	// no validation rules for Status

	// no validation rules for Input

	// no validation rules for Output

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CronExecutionValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CronExecutionValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CronExecutionValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetFinishedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CronExecutionValidationError{
					field:  "FinishedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CronExecutionValidationError{
					field:  "FinishedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFinishedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CronExecutionValidationError{
				field:  "FinishedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for WorkspaceId

	if len(errors) > 0 {
		return CronExecutionMultiError(errors)
	}

	return nil
}

// CronExecutionMultiError is an error wrapping multiple validation errors
// returned by CronExecution.ValidateAll() if the designated constraints
// aren't met.
type CronExecutionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CronExecutionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CronExecutionMultiError) AllErrors() []error { return m }

// CronExecutionValidationError is the validation error returned by
// CronExecution.Validate if the designated constraints aren't met.
type CronExecutionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CronExecutionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CronExecutionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CronExecutionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CronExecutionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CronExecutionValidationError) ErrorName() string { return "CronExecutionValidationError" }

// Error satisfies the builtin error interface
func (e CronExecutionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCronExecution.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CronExecutionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CronExecutionValidationError{}

// Validate checks the field values on ListCronJobsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCronJobsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCronJobsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCronJobsRequestMultiError, or nil if none found.
func (m *ListCronJobsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCronJobsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListCronJobsRequestMultiError(errors)
	}

	return nil
}

// ListCronJobsRequestMultiError is an error wrapping multiple validation
// errors returned by ListCronJobsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListCronJobsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCronJobsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCronJobsRequestMultiError) AllErrors() []error { return m }

// ListCronJobsRequestValidationError is the validation error returned by
// ListCronJobsRequest.Validate if the designated constraints aren't met.
type ListCronJobsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCronJobsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCronJobsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCronJobsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCronJobsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCronJobsRequestValidationError) ErrorName() string {
	return "ListCronJobsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListCronJobsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCronJobsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCronJobsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCronJobsRequestValidationError{}

// Validate checks the field values on ListCronJobsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCronJobsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCronJobsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCronJobsResponseMultiError, or nil if none found.
func (m *ListCronJobsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCronJobsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetCronJobs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListCronJobsResponseValidationError{
						field:  fmt.Sprintf("CronJobs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListCronJobsResponseValidationError{
						field:  fmt.Sprintf("CronJobs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListCronJobsResponseValidationError{
					field:  fmt.Sprintf("CronJobs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListCronJobsResponseMultiError(errors)
	}

	return nil
}

// ListCronJobsResponseMultiError is an error wrapping multiple validation
// errors returned by ListCronJobsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListCronJobsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCronJobsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCronJobsResponseMultiError) AllErrors() []error { return m }

// ListCronJobsResponseValidationError is the validation error returned by
// ListCronJobsResponse.Validate if the designated constraints aren't met.
type ListCronJobsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCronJobsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCronJobsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCronJobsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCronJobsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCronJobsResponseValidationError) ErrorName() string {
	return "ListCronJobsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListCronJobsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCronJobsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCronJobsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCronJobsResponseValidationError{}

// Validate checks the field values on GetCronJobRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetCronJobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCronJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCronJobRequestMultiError, or nil if none found.
func (m *GetCronJobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCronJobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return GetCronJobRequestMultiError(errors)
	}

	return nil
}

// GetCronJobRequestMultiError is an error wrapping multiple validation errors
// returned by GetCronJobRequest.ValidateAll() if the designated constraints
// aren't met.
type GetCronJobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCronJobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCronJobRequestMultiError) AllErrors() []error { return m }

// GetCronJobRequestValidationError is the validation error returned by
// GetCronJobRequest.Validate if the designated constraints aren't met.
type GetCronJobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCronJobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCronJobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCronJobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCronJobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCronJobRequestValidationError) ErrorName() string {
	return "GetCronJobRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCronJobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCronJobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCronJobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCronJobRequestValidationError{}

// Validate checks the field values on CreateCronJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateCronJobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCronJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCronJobRequestMultiError, or nil if none found.
func (m *CreateCronJobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCronJobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCronJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateCronJobRequestValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateCronJobRequestValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCronJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateCronJobRequestValidationError{
				field:  "CronJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateCronJobRequestMultiError(errors)
	}

	return nil
}

// CreateCronJobRequestMultiError is an error wrapping multiple validation
// errors returned by CreateCronJobRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateCronJobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCronJobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCronJobRequestMultiError) AllErrors() []error { return m }

// CreateCronJobRequestValidationError is the validation error returned by
// CreateCronJobRequest.Validate if the designated constraints aren't met.
type CreateCronJobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCronJobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCronJobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCronJobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCronJobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCronJobRequestValidationError) ErrorName() string {
	return "CreateCronJobRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCronJobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCronJobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCronJobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCronJobRequestValidationError{}

// Validate checks the field values on UpdateCronJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateCronJobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateCronJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateCronJobRequestMultiError, or nil if none found.
func (m *UpdateCronJobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateCronJobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCronJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateCronJobRequestValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateCronJobRequestValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCronJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateCronJobRequestValidationError{
				field:  "CronJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateCronJobRequestMultiError(errors)
	}

	return nil
}

// UpdateCronJobRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateCronJobRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateCronJobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateCronJobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateCronJobRequestMultiError) AllErrors() []error { return m }

// UpdateCronJobRequestValidationError is the validation error returned by
// UpdateCronJobRequest.Validate if the designated constraints aren't met.
type UpdateCronJobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateCronJobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateCronJobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateCronJobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateCronJobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateCronJobRequestValidationError) ErrorName() string {
	return "UpdateCronJobRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateCronJobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateCronJobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateCronJobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateCronJobRequestValidationError{}

// Validate checks the field values on DeleteCronJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteCronJobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteCronJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteCronJobRequestMultiError, or nil if none found.
func (m *DeleteCronJobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteCronJobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return DeleteCronJobRequestMultiError(errors)
	}

	return nil
}

// DeleteCronJobRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteCronJobRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteCronJobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteCronJobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteCronJobRequestMultiError) AllErrors() []error { return m }

// DeleteCronJobRequestValidationError is the validation error returned by
// DeleteCronJobRequest.Validate if the designated constraints aren't met.
type DeleteCronJobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteCronJobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteCronJobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteCronJobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteCronJobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteCronJobRequestValidationError) ErrorName() string {
	return "DeleteCronJobRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteCronJobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteCronJobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteCronJobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteCronJobRequestValidationError{}

// Validate checks the field values on GetCronJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCronJobResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCronJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCronJobResponseMultiError, or nil if none found.
func (m *GetCronJobResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCronJobResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCronJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetCronJobResponseValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetCronJobResponseValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCronJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetCronJobResponseValidationError{
				field:  "CronJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetCronJobResponseMultiError(errors)
	}

	return nil
}

// GetCronJobResponseMultiError is an error wrapping multiple validation errors
// returned by GetCronJobResponse.ValidateAll() if the designated constraints
// aren't met.
type GetCronJobResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCronJobResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCronJobResponseMultiError) AllErrors() []error { return m }

// GetCronJobResponseValidationError is the validation error returned by
// GetCronJobResponse.Validate if the designated constraints aren't met.
type GetCronJobResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCronJobResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCronJobResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCronJobResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCronJobResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCronJobResponseValidationError) ErrorName() string {
	return "GetCronJobResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetCronJobResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCronJobResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCronJobResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCronJobResponseValidationError{}

// Validate checks the field values on CreateCronJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateCronJobResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCronJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCronJobResponseMultiError, or nil if none found.
func (m *CreateCronJobResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCronJobResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCronJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateCronJobResponseValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateCronJobResponseValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCronJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateCronJobResponseValidationError{
				field:  "CronJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateCronJobResponseMultiError(errors)
	}

	return nil
}

// CreateCronJobResponseMultiError is an error wrapping multiple validation
// errors returned by CreateCronJobResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateCronJobResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCronJobResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCronJobResponseMultiError) AllErrors() []error { return m }

// CreateCronJobResponseValidationError is the validation error returned by
// CreateCronJobResponse.Validate if the designated constraints aren't met.
type CreateCronJobResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCronJobResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCronJobResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCronJobResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCronJobResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCronJobResponseValidationError) ErrorName() string {
	return "CreateCronJobResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCronJobResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCronJobResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCronJobResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCronJobResponseValidationError{}

// Validate checks the field values on UpdateCronJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateCronJobResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateCronJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateCronJobResponseMultiError, or nil if none found.
func (m *UpdateCronJobResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateCronJobResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCronJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateCronJobResponseValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateCronJobResponseValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCronJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateCronJobResponseValidationError{
				field:  "CronJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateCronJobResponseMultiError(errors)
	}

	return nil
}

// UpdateCronJobResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateCronJobResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateCronJobResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateCronJobResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateCronJobResponseMultiError) AllErrors() []error { return m }

// UpdateCronJobResponseValidationError is the validation error returned by
// UpdateCronJobResponse.Validate if the designated constraints aren't met.
type UpdateCronJobResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateCronJobResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateCronJobResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateCronJobResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateCronJobResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateCronJobResponseValidationError) ErrorName() string {
	return "UpdateCronJobResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateCronJobResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateCronJobResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateCronJobResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateCronJobResponseValidationError{}

// Validate checks the field values on DeleteCronJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteCronJobResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteCronJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteCronJobResponseMultiError, or nil if none found.
func (m *DeleteCronJobResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteCronJobResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCronJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeleteCronJobResponseValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeleteCronJobResponseValidationError{
					field:  "CronJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCronJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeleteCronJobResponseValidationError{
				field:  "CronJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeleteCronJobResponseMultiError(errors)
	}

	return nil
}

// DeleteCronJobResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteCronJobResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteCronJobResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteCronJobResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteCronJobResponseMultiError) AllErrors() []error { return m }

// DeleteCronJobResponseValidationError is the validation error returned by
// DeleteCronJobResponse.Validate if the designated constraints aren't met.
type DeleteCronJobResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteCronJobResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteCronJobResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteCronJobResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteCronJobResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteCronJobResponseValidationError) ErrorName() string {
	return "DeleteCronJobResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteCronJobResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteCronJobResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteCronJobResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteCronJobResponseValidationError{}

// Validate checks the field values on ListCronExecutionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCronExecutionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCronExecutionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCronExecutionsRequestMultiError, or nil if none found.
func (m *ListCronExecutionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCronExecutionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for JobName

	// no validation rules for PageSize

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListCronExecutionsRequestMultiError(errors)
	}

	return nil
}

// ListCronExecutionsRequestMultiError is an error wrapping multiple validation
// errors returned by ListCronExecutionsRequest.ValidateAll() if the
// designated constraints aren't met.
type ListCronExecutionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCronExecutionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCronExecutionsRequestMultiError) AllErrors() []error { return m }

// ListCronExecutionsRequestValidationError is the validation error returned by
// ListCronExecutionsRequest.Validate if the designated constraints aren't met.
type ListCronExecutionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCronExecutionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCronExecutionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCronExecutionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCronExecutionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCronExecutionsRequestValidationError) ErrorName() string {
	return "ListCronExecutionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListCronExecutionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCronExecutionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCronExecutionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCronExecutionsRequestValidationError{}

// Validate checks the field values on RunCronJobNowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RunCronJobNowRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RunCronJobNowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RunCronJobNowRequestMultiError, or nil if none found.
func (m *RunCronJobNowRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RunCronJobNowRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := RunCronJobNowRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RunCronJobNowRequestMultiError(errors)
	}

	return nil
}

// RunCronJobNowRequestMultiError is an error wrapping multiple validation
// errors returned by RunCronJobNowRequest.ValidateAll() if the designated
// constraints aren't met.
type RunCronJobNowRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RunCronJobNowRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RunCronJobNowRequestMultiError) AllErrors() []error { return m }

// RunCronJobNowRequestValidationError is the validation error returned by
// RunCronJobNowRequest.Validate if the designated constraints aren't met.
type RunCronJobNowRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RunCronJobNowRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RunCronJobNowRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RunCronJobNowRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RunCronJobNowRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RunCronJobNowRequestValidationError) ErrorName() string {
	return "RunCronJobNowRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RunCronJobNowRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRunCronJobNowRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RunCronJobNowRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RunCronJobNowRequestValidationError{}

// Validate checks the field values on RunCronJobNowResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RunCronJobNowResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RunCronJobNowResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RunCronJobNowResponseMultiError, or nil if none found.
func (m *RunCronJobNowResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RunCronJobNowResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetExecution()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RunCronJobNowResponseValidationError{
					field:  "Execution",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RunCronJobNowResponseValidationError{
					field:  "Execution",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExecution()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RunCronJobNowResponseValidationError{
				field:  "Execution",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RunCronJobNowResponseMultiError(errors)
	}

	return nil
}

// RunCronJobNowResponseMultiError is an error wrapping multiple validation
// errors returned by RunCronJobNowResponse.ValidateAll() if the designated
// constraints aren't met.
type RunCronJobNowResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RunCronJobNowResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RunCronJobNowResponseMultiError) AllErrors() []error { return m }

// RunCronJobNowResponseValidationError is the validation error returned by
// RunCronJobNowResponse.Validate if the designated constraints aren't met.
type RunCronJobNowResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RunCronJobNowResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RunCronJobNowResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RunCronJobNowResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RunCronJobNowResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RunCronJobNowResponseValidationError) ErrorName() string {
	return "RunCronJobNowResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RunCronJobNowResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRunCronJobNowResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RunCronJobNowResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RunCronJobNowResponseValidationError{}

// Validate checks the field values on ListCronExecutionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCronExecutionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCronExecutionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCronExecutionsResponseMultiError, or nil if none found.
func (m *ListCronExecutionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCronExecutionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetExecutions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListCronExecutionsResponseValidationError{
						field:  fmt.Sprintf("Executions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListCronExecutionsResponseValidationError{
						field:  fmt.Sprintf("Executions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListCronExecutionsResponseValidationError{
					field:  fmt.Sprintf("Executions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListCronExecutionsResponseMultiError(errors)
	}

	return nil
}

// ListCronExecutionsResponseMultiError is an error wrapping multiple
// validation errors returned by ListCronExecutionsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListCronExecutionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCronExecutionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCronExecutionsResponseMultiError) AllErrors() []error { return m }

// ListCronExecutionsResponseValidationError is the validation error returned
// by ListCronExecutionsResponse.Validate if the designated constraints aren't met.
type ListCronExecutionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCronExecutionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCronExecutionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCronExecutionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCronExecutionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCronExecutionsResponseValidationError) ErrorName() string {
	return "ListCronExecutionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListCronExecutionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCronExecutionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCronExecutionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCronExecutionsResponseValidationError{}
