// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: agents/v1/daemon.proto

package agentsv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DaemonInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DaemonInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DaemonInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DaemonInfoMultiError, or
// nil if none found.
func (m *DaemonInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *DaemonInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DaemonId

	// no validation rules for Name

	// no validation rules for Labels

	// no validation rules for Version

	// no validation rules for Os

	if len(errors) > 0 {
		return DaemonInfoMultiError(errors)
	}

	return nil
}

// DaemonInfoMultiError is an error wrapping multiple validation errors
// returned by DaemonInfo.ValidateAll() if the designated constraints aren't met.
type DaemonInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DaemonInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DaemonInfoMultiError) AllErrors() []error { return m }

// DaemonInfoValidationError is the validation error returned by
// DaemonInfo.Validate if the designated constraints aren't met.
type DaemonInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DaemonInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DaemonInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DaemonInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DaemonInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DaemonInfoValidationError) ErrorName() string { return "DaemonInfoValidationError" }

// Error satisfies the builtin error interface
func (e DaemonInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDaemonInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DaemonInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DaemonInfoValidationError{}

// Validate checks the field values on DaemonTask with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DaemonTask) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DaemonTask with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DaemonTaskMultiError, or
// nil if none found.
func (m *DaemonTask) ValidateAll() error {
	return m.validate(true)
}

func (m *DaemonTask) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for AgentName

	// no validation rules for Input

	// no validation rules for SessionId

	// no validation rules for UserId

	// no validation rules for Metadata

	// no validation rules for Capability

	if len(errors) > 0 {
		return DaemonTaskMultiError(errors)
	}

	return nil
}

// DaemonTaskMultiError is an error wrapping multiple validation errors
// returned by DaemonTask.ValidateAll() if the designated constraints aren't met.
type DaemonTaskMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DaemonTaskMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DaemonTaskMultiError) AllErrors() []error { return m }

// DaemonTaskValidationError is the validation error returned by
// DaemonTask.Validate if the designated constraints aren't met.
type DaemonTaskValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DaemonTaskValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DaemonTaskValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DaemonTaskValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DaemonTaskValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DaemonTaskValidationError) ErrorName() string { return "DaemonTaskValidationError" }

// Error satisfies the builtin error interface
func (e DaemonTaskValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDaemonTask.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DaemonTaskValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DaemonTaskValidationError{}

// Validate checks the field values on DaemonTaskUpdate with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DaemonTaskUpdate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DaemonTaskUpdate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DaemonTaskUpdateMultiError, or nil if none found.
func (m *DaemonTaskUpdate) ValidateAll() error {
	return m.validate(true)
}

func (m *DaemonTaskUpdate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for Status

	// no validation rules for Output

	// no validation rules for Error

	if all {
		switch v := interface{}(m.GetTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DaemonTaskUpdateValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DaemonTaskUpdateValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DaemonTaskUpdateValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CurrentStep

	// no validation rules for Progress

	if len(errors) > 0 {
		return DaemonTaskUpdateMultiError(errors)
	}

	return nil
}

// DaemonTaskUpdateMultiError is an error wrapping multiple validation errors
// returned by DaemonTaskUpdate.ValidateAll() if the designated constraints
// aren't met.
type DaemonTaskUpdateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DaemonTaskUpdateMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DaemonTaskUpdateMultiError) AllErrors() []error { return m }

// DaemonTaskUpdateValidationError is the validation error returned by
// DaemonTaskUpdate.Validate if the designated constraints aren't met.
type DaemonTaskUpdateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DaemonTaskUpdateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DaemonTaskUpdateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DaemonTaskUpdateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DaemonTaskUpdateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DaemonTaskUpdateValidationError) ErrorName() string { return "DaemonTaskUpdateValidationError" }

// Error satisfies the builtin error interface
func (e DaemonTaskUpdateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDaemonTaskUpdate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DaemonTaskUpdateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DaemonTaskUpdateValidationError{}

// Validate checks the field values on CancelTask with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CancelTask) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelTask with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CancelTaskMultiError, or
// nil if none found.
func (m *CancelTask) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelTask) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	if len(errors) > 0 {
		return CancelTaskMultiError(errors)
	}

	return nil
}

// CancelTaskMultiError is an error wrapping multiple validation errors
// returned by CancelTask.ValidateAll() if the designated constraints aren't met.
type CancelTaskMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelTaskMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelTaskMultiError) AllErrors() []error { return m }

// CancelTaskValidationError is the validation error returned by
// CancelTask.Validate if the designated constraints aren't met.
type CancelTaskValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelTaskValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelTaskValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelTaskValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelTaskValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelTaskValidationError) ErrorName() string { return "CancelTaskValidationError" }

// Error satisfies the builtin error interface
func (e CancelTaskValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelTask.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelTaskValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelTaskValidationError{}

// Validate checks the field values on ConnectRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConnectRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConnectRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConnectRequestMultiError,
// or nil if none found.
func (m *ConnectRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConnectRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Message.(type) {
	case *ConnectRequest_Register:
		if v == nil {
			err := ConnectRequestValidationError{
				field:  "Message",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetRegister()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConnectRequestValidationError{
						field:  "Register",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConnectRequestValidationError{
						field:  "Register",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRegister()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConnectRequestValidationError{
					field:  "Register",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ConnectRequest_TaskUpdate:
		if v == nil {
			err := ConnectRequestValidationError{
				field:  "Message",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetTaskUpdate()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConnectRequestValidationError{
						field:  "TaskUpdate",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConnectRequestValidationError{
						field:  "TaskUpdate",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTaskUpdate()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConnectRequestValidationError{
					field:  "TaskUpdate",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ConnectRequestMultiError(errors)
	}

	return nil
}

// ConnectRequestMultiError is an error wrapping multiple validation errors
// returned by ConnectRequest.ValidateAll() if the designated constraints
// aren't met.
type ConnectRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConnectRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConnectRequestMultiError) AllErrors() []error { return m }

// ConnectRequestValidationError is the validation error returned by
// ConnectRequest.Validate if the designated constraints aren't met.
type ConnectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConnectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConnectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConnectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConnectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConnectRequestValidationError) ErrorName() string { return "ConnectRequestValidationError" }

// Error satisfies the builtin error interface
func (e ConnectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConnectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConnectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConnectRequestValidationError{}

// Validate checks the field values on ConnectResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConnectResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConnectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConnectResponseMultiError, or nil if none found.
func (m *ConnectResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ConnectResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Message.(type) {
	case *ConnectResponse_Task:
		if v == nil {
			err := ConnectResponseValidationError{
				field:  "Message",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetTask()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConnectResponseValidationError{
						field:  "Task",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConnectResponseValidationError{
						field:  "Task",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTask()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConnectResponseValidationError{
					field:  "Task",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ConnectResponse_Cancel:
		if v == nil {
			err := ConnectResponseValidationError{
				field:  "Message",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetCancel()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConnectResponseValidationError{
						field:  "Cancel",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConnectResponseValidationError{
						field:  "Cancel",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCancel()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConnectResponseValidationError{
					field:  "Cancel",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ConnectResponseMultiError(errors)
	}

	return nil
}

// ConnectResponseMultiError is an error wrapping multiple validation errors
// returned by ConnectResponse.ValidateAll() if the designated constraints
// aren't met.
type ConnectResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConnectResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConnectResponseMultiError) AllErrors() []error { return m }

// ConnectResponseValidationError is the validation error returned by
// ConnectResponse.Validate if the designated constraints aren't met.
type ConnectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConnectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConnectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConnectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConnectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConnectResponseValidationError) ErrorName() string { return "ConnectResponseValidationError" }

// Error satisfies the builtin error interface
func (e ConnectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConnectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConnectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConnectResponseValidationError{}
