// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: agents/v1/daemon.proto

package agentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DaemonTaskStatus tracks the lifecycle of a daemon task.
type DaemonTaskStatus int32

const (
	DaemonTaskStatus_DAEMON_TASK_STATUS_UNSPECIFIED DaemonTaskStatus = 0
	DaemonTaskStatus_DAEMON_TASK_STATUS_ACCEPTED    DaemonTaskStatus = 1
	DaemonTaskStatus_DAEMON_TASK_STATUS_RUNNING     DaemonTaskStatus = 2
	DaemonTaskStatus_DAEMON_TASK_STATUS_COMPLETED   DaemonTaskStatus = 3
	DaemonTaskStatus_DAEMON_TASK_STATUS_FAILED      DaemonTaskStatus = 4
	DaemonTaskStatus_DAEMON_TASK_STATUS_CANCELLED   DaemonTaskStatus = 5
)

// Enum value maps for DaemonTaskStatus.
var (
	DaemonTaskStatus_name = map[int32]string{
		0: "DAEMON_TASK_STATUS_UNSPECIFIED",
		1: "DAEMON_TASK_STATUS_ACCEPTED",
		2: "DAEMON_TASK_STATUS_RUNNING",
		3: "DAEMON_TASK_STATUS_COMPLETED",
		4: "DAEMON_TASK_STATUS_FAILED",
		5: "DAEMON_TASK_STATUS_CANCELLED",
	}
	DaemonTaskStatus_value = map[string]int32{
		"DAEMON_TASK_STATUS_UNSPECIFIED": 0,
		"DAEMON_TASK_STATUS_ACCEPTED":    1,
		"DAEMON_TASK_STATUS_RUNNING":     2,
		"DAEMON_TASK_STATUS_COMPLETED":   3,
		"DAEMON_TASK_STATUS_FAILED":      4,
		"DAEMON_TASK_STATUS_CANCELLED":   5,
	}
)

func (x DaemonTaskStatus) Enum() *DaemonTaskStatus {
	p := new(DaemonTaskStatus)
	*p = x
	return p
}

func (x DaemonTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DaemonTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agents_v1_daemon_proto_enumTypes[0].Descriptor()
}

func (DaemonTaskStatus) Type() protoreflect.EnumType {
	return &file_agents_v1_daemon_proto_enumTypes[0]
}

func (x DaemonTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DaemonTaskStatus.Descriptor instead.
func (DaemonTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{0}
}

// DaemonInfo is sent by the daemon client as the first message on the
// Connect stream to register itself with the server.
type DaemonInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Runtime this daemon connection serves. The server derives the
	// authoritative value from the daemon token and overwrites any client value.
	// @gotags: json:"daemon_runtime_id,omitempty" yaml:"daemon_runtime_id,omitempty"
	DaemonRuntimeId string `protobuf:"bytes,1,opt,name=daemon_runtime_id,json=daemonRuntimeId,proto3" json:"daemon_runtime_id,omitempty" yaml:"daemon_runtime_id,omitempty"`
	// Human-readable name for this daemon.
	// @gotags: json:"name,omitempty" yaml:"name,omitempty"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" yaml:"name,omitempty"`
	// ACP runtimes supported by this daemon binary. In v1 this is fixed to
	// ["opencode", "codex"] by the client.
	// @gotags: json:"acp_runtimes,omitempty" yaml:"acp_runtimes,omitempty"
	AcpRuntimes []string `protobuf:"bytes,3,rep,name=acp_runtimes,json=acpRuntimes,proto3" json:"acp_runtimes,omitempty" yaml:"acp_runtimes,omitempty"`
	// Routing labels (reserved for future use; not used for selection in Phase 1).
	// @gotags: json:"labels,omitempty" yaml:"labels,omitempty"
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" yaml:"labels,omitempty"`
	// Semantic version of the daemon client binary (e.g. "v1.4.2").
	// @gotags: json:"version,omitempty" yaml:"version,omitempty"
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty" yaml:"version,omitempty"`
	// Operating system identifier (e.g. "linux-amd64", "darwin-arm64").
	// @gotags: json:"os,omitempty" yaml:"os,omitempty"
	Os string `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty" yaml:"os,omitempty"`
	// Optional executor names the daemon will use. Surfaced to the dashboard for
	// diagnostics. ACP runtime remains the routing primitive.
	// @gotags: json:"executors,omitempty" yaml:"executors,omitempty"
	Executors []string `protobuf:"bytes,7,rep,name=executors,proto3" json:"executors,omitempty" yaml:"executors,omitempty"`
	// Workspace this runtime belongs to. The server derives the authoritative
	// workspace from the daemon credential and rejects mismatches.
	// @gotags: json:"workspace_id,omitempty" yaml:"workspace_id,omitempty"
	WorkspaceId string `protobuf:"bytes,8,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty" yaml:"workspace_id,omitempty"`
}

func (x *DaemonInfo) Reset() {
	*x = DaemonInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonInfo) ProtoMessage() {}

func (x *DaemonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonInfo.ProtoReflect.Descriptor instead.
func (*DaemonInfo) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *DaemonInfo) GetDaemonRuntimeId() string {
	if x != nil {
		return x.DaemonRuntimeId
	}
	return ""
}

func (x *DaemonInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DaemonInfo) GetAcpRuntimes() []string {
	if x != nil {
		return x.AcpRuntimes
	}
	return nil
}

func (x *DaemonInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DaemonInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DaemonInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DaemonInfo) GetExecutors() []string {
	if x != nil {
		return x.Executors
	}
	return nil
}

func (x *DaemonInfo) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

// DaemonTask is a task assignment sent from server to daemon.
type DaemonTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"task_id,omitempty" yaml:"task_id,omitempty"
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty" yaml:"task_id,omitempty"`
	// The agent name on the server side that triggered this task.
	// @gotags: json:"agent_name,omitempty" yaml:"agent_name,omitempty"
	AgentName string `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty" yaml:"agent_name,omitempty"`
	// User input text to execute.
	// @gotags: json:"input,omitempty" yaml:"input,omitempty"
	Input string `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty" yaml:"input,omitempty"`
	// @gotags: json:"session_id,omitempty" yaml:"session_id,omitempty"
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty" yaml:"session_id,omitempty"`
	// @gotags: json:"user_id,omitempty" yaml:"user_id,omitempty"
	UserId string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" yaml:"user_id,omitempty"`
	// @gotags: json:"metadata,omitempty" yaml:"metadata,omitempty"
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" yaml:"metadata,omitempty"`
	// Workspace that owns this task.
	// @gotags: json:"workspace_id,omitempty" yaml:"workspace_id,omitempty"
	WorkspaceId string `protobuf:"bytes,8,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty" yaml:"workspace_id,omitempty"`
	// Runtime that should execute this task.
	// @gotags: json:"daemon_runtime_id,omitempty" yaml:"daemon_runtime_id,omitempty"
	DaemonRuntimeId string `protobuf:"bytes,9,opt,name=daemon_runtime_id,json=daemonRuntimeId,proto3" json:"daemon_runtime_id,omitempty" yaml:"daemon_runtime_id,omitempty"`
	// ACP runtime selected by the daemon-backed remote agent, e.g. "opencode"
	// or "codex".
	// @gotags: json:"acp_runtime,omitempty" yaml:"acp_runtime,omitempty"
	AcpRuntime string `protobuf:"bytes,10,opt,name=acp_runtime,json=acpRuntime,proto3" json:"acp_runtime,omitempty" yaml:"acp_runtime,omitempty"`
	// Working directory for this invocation. The first implementation generates
	// this under /tmp from workspace + session identity.
	// @gotags: json:"work_dir,omitempty" yaml:"work_dir,omitempty"
	WorkDir string `protobuf:"bytes,11,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty" yaml:"work_dir,omitempty"`
}

func (x *DaemonTask) Reset() {
	*x = DaemonTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonTask) ProtoMessage() {}

func (x *DaemonTask) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonTask.ProtoReflect.Descriptor instead.
func (*DaemonTask) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *DaemonTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DaemonTask) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *DaemonTask) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *DaemonTask) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DaemonTask) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DaemonTask) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DaemonTask) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DaemonTask) GetDaemonRuntimeId() string {
	if x != nil {
		return x.DaemonRuntimeId
	}
	return ""
}

func (x *DaemonTask) GetAcpRuntime() string {
	if x != nil {
		return x.AcpRuntime
	}
	return ""
}

func (x *DaemonTask) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

// DaemonTaskUpdate is sent from daemon to server to report task progress or results.
type DaemonTaskUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"task_id,omitempty" yaml:"task_id,omitempty"
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty" yaml:"task_id,omitempty"`
	// @gotags: json:"status,omitempty" yaml:"status,omitempty"
	Status DaemonTaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=agents.v1.DaemonTaskStatus" json:"status,omitempty" yaml:"status,omitempty"`
	// Partial or final output text.
	// @gotags: json:"output,omitempty" yaml:"output,omitempty"
	Output string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty" yaml:"output,omitempty"`
	// Error message (populated when status is FAILED).
	// @gotags: json:"error,omitempty" yaml:"error,omitempty"
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty" yaml:"error,omitempty"`
	// @gotags: json:"timestamp,omitempty" yaml:"timestamp,omitempty"
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty" yaml:"timestamp,omitempty"`
	// Optional short label for the current step (e.g. "Compiling dependencies").
	// @gotags: json:"current_step,omitempty" yaml:"current_step,omitempty"
	CurrentStep string `protobuf:"bytes,6,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty" yaml:"current_step,omitempty"`
	// Optional progress percentage in [0, 100]. 0 when unknown.
	// @gotags: json:"progress,omitempty" yaml:"progress,omitempty"
	Progress int32 `protobuf:"varint,7,opt,name=progress,proto3" json:"progress,omitempty" yaml:"progress,omitempty"`
}

func (x *DaemonTaskUpdate) Reset() {
	*x = DaemonTaskUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonTaskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonTaskUpdate) ProtoMessage() {}

func (x *DaemonTaskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonTaskUpdate.ProtoReflect.Descriptor instead.
func (*DaemonTaskUpdate) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *DaemonTaskUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DaemonTaskUpdate) GetStatus() DaemonTaskStatus {
	if x != nil {
		return x.Status
	}
	return DaemonTaskStatus_DAEMON_TASK_STATUS_UNSPECIFIED
}

func (x *DaemonTaskUpdate) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *DaemonTaskUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DaemonTaskUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DaemonTaskUpdate) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *DaemonTaskUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

// CancelTask requests cancellation of a running task.
type CancelTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"task_id,omitempty" yaml:"task_id,omitempty"
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty" yaml:"task_id,omitempty"`
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *CancelTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DaemonConnectorServiceRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Daemon *DaemonInfo `protobuf:"bytes,1,opt,name=daemon,proto3" json:"daemon,omitempty"`
}

func (x *DaemonConnectorServiceRegisterRequest) Reset() {
	*x = DaemonConnectorServiceRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConnectorServiceRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConnectorServiceRegisterRequest) ProtoMessage() {}

func (x *DaemonConnectorServiceRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConnectorServiceRegisterRequest.ProtoReflect.Descriptor instead.
func (*DaemonConnectorServiceRegisterRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *DaemonConnectorServiceRegisterRequest) GetDaemon() *DaemonInfo {
	if x != nil {
		return x.Daemon
	}
	return nil
}

type DaemonConnectorServiceRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Daemon *DaemonInfo `protobuf:"bytes,1,opt,name=daemon,proto3" json:"daemon,omitempty"`
}

func (x *DaemonConnectorServiceRegisterResponse) Reset() {
	*x = DaemonConnectorServiceRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConnectorServiceRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConnectorServiceRegisterResponse) ProtoMessage() {}

func (x *DaemonConnectorServiceRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConnectorServiceRegisterResponse.ProtoReflect.Descriptor instead.
func (*DaemonConnectorServiceRegisterResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *DaemonConnectorServiceRegisterResponse) GetDaemon() *DaemonInfo {
	if x != nil {
		return x.Daemon
	}
	return nil
}

type DaemonConnectorServicePollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Maximum time the server should wait for a task before returning empty.
	WaitTimeout *durationpb.Duration `protobuf:"bytes,1,opt,name=wait_timeout,json=waitTimeout,proto3" json:"wait_timeout,omitempty"`
}

func (x *DaemonConnectorServicePollRequest) Reset() {
	*x = DaemonConnectorServicePollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConnectorServicePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConnectorServicePollRequest) ProtoMessage() {}

func (x *DaemonConnectorServicePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConnectorServicePollRequest.ProtoReflect.Descriptor instead.
func (*DaemonConnectorServicePollRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *DaemonConnectorServicePollRequest) GetWaitTimeout() *durationpb.Duration {
	if x != nil {
		return x.WaitTimeout
	}
	return nil
}

type DaemonConnectorServicePollResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*ConnectResponse `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *DaemonConnectorServicePollResponse) Reset() {
	*x = DaemonConnectorServicePollResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConnectorServicePollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConnectorServicePollResponse) ProtoMessage() {}

func (x *DaemonConnectorServicePollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConnectorServicePollResponse.ProtoReflect.Descriptor instead.
func (*DaemonConnectorServicePollResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *DaemonConnectorServicePollResponse) GetMessages() []*ConnectResponse {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DaemonConnectorServiceReportTaskUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Update *DaemonTaskUpdate `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *DaemonConnectorServiceReportTaskUpdateRequest) Reset() {
	*x = DaemonConnectorServiceReportTaskUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConnectorServiceReportTaskUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConnectorServiceReportTaskUpdateRequest) ProtoMessage() {}

func (x *DaemonConnectorServiceReportTaskUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConnectorServiceReportTaskUpdateRequest.ProtoReflect.Descriptor instead.
func (*DaemonConnectorServiceReportTaskUpdateRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *DaemonConnectorServiceReportTaskUpdateRequest) GetUpdate() *DaemonTaskUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

type DaemonConnectorServiceReportTaskUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DaemonConnectorServiceReportTaskUpdateResponse) Reset() {
	*x = DaemonConnectorServiceReportTaskUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConnectorServiceReportTaskUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConnectorServiceReportTaskUpdateResponse) ProtoMessage() {}

func (x *DaemonConnectorServiceReportTaskUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConnectorServiceReportTaskUpdateResponse.ProtoReflect.Descriptor instead.
func (*DaemonConnectorServiceReportTaskUpdateResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{9}
}

type DaemonConnectorServiceUnregisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DaemonConnectorServiceUnregisterRequest) Reset() {
	*x = DaemonConnectorServiceUnregisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConnectorServiceUnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConnectorServiceUnregisterRequest) ProtoMessage() {}

func (x *DaemonConnectorServiceUnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConnectorServiceUnregisterRequest.ProtoReflect.Descriptor instead.
func (*DaemonConnectorServiceUnregisterRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{10}
}

type DaemonConnectorServiceUnregisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DaemonConnectorServiceUnregisterResponse) Reset() {
	*x = DaemonConnectorServiceUnregisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConnectorServiceUnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConnectorServiceUnregisterResponse) ProtoMessage() {}

func (x *DaemonConnectorServiceUnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConnectorServiceUnregisterResponse.ProtoReflect.Descriptor instead.
func (*DaemonConnectorServiceUnregisterResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{11}
}

// ConnectRequest is the client-to-server stream message for DaemonConnectorService.Connect.
type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ConnectRequest_Register
	//	*ConnectRequest_TaskUpdate
	//	*ConnectRequest_Heartbeat
	Message isConnectRequest_Message `protobuf_oneof:"message"`
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{12}
}

func (m *ConnectRequest) GetMessage() isConnectRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ConnectRequest) GetRegister() *DaemonInfo {
	if x, ok := x.GetMessage().(*ConnectRequest_Register); ok {
		return x.Register
	}
	return nil
}

func (x *ConnectRequest) GetTaskUpdate() *DaemonTaskUpdate {
	if x, ok := x.GetMessage().(*ConnectRequest_TaskUpdate); ok {
		return x.TaskUpdate
	}
	return nil
}

func (x *ConnectRequest) GetHeartbeat() *emptypb.Empty {
	if x, ok := x.GetMessage().(*ConnectRequest_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

type isConnectRequest_Message interface {
	isConnectRequest_Message()
}

type ConnectRequest_Register struct {
	// First message must be a register.
	Register *DaemonInfo `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ConnectRequest_TaskUpdate struct {
	// Subsequent messages are task updates.
	TaskUpdate *DaemonTaskUpdate `protobuf:"bytes,2,opt,name=task_update,json=taskUpdate,proto3,oneof"`
}

type ConnectRequest_Heartbeat struct {
	// Heartbeat keeps long-lived streams active through proxies.
	Heartbeat *emptypb.Empty `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*ConnectRequest_Register) isConnectRequest_Message() {}

func (*ConnectRequest_TaskUpdate) isConnectRequest_Message() {}

func (*ConnectRequest_Heartbeat) isConnectRequest_Message() {}

// ConnectResponse is the server-to-client stream message for DaemonConnectorService.Connect.
type ConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ConnectResponse_Task
	//	*ConnectResponse_Cancel
	//	*ConnectResponse_Heartbeat
	Message isConnectResponse_Message `protobuf_oneof:"message"`
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_v1_daemon_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_v1_daemon_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_agents_v1_daemon_proto_rawDescGZIP(), []int{13}
}

func (m *ConnectResponse) GetMessage() isConnectResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ConnectResponse) GetTask() *DaemonTask {
	if x, ok := x.GetMessage().(*ConnectResponse_Task); ok {
		return x.Task
	}
	return nil
}

func (x *ConnectResponse) GetCancel() *CancelTask {
	if x, ok := x.GetMessage().(*ConnectResponse_Cancel); ok {
		return x.Cancel
	}
	return nil
}

func (x *ConnectResponse) GetHeartbeat() *emptypb.Empty {
	if x, ok := x.GetMessage().(*ConnectResponse_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

type isConnectResponse_Message interface {
	isConnectResponse_Message()
}

type ConnectResponse_Task struct {
	// Task assignment.
	Task *DaemonTask `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type ConnectResponse_Cancel struct {
	// Cancel a running task.
	Cancel *CancelTask `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

type ConnectResponse_Heartbeat struct {
	// Heartbeat keeps long-lived streams active through proxies.
	Heartbeat *emptypb.Empty `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*ConnectResponse_Task) isConnectResponse_Message() {}

func (*ConnectResponse_Cancel) isConnectResponse_Message() {}

func (*ConnectResponse_Heartbeat) isConnectResponse_Message() {}

var File_agents_v1_daemon_proto protoreflect.FileDescriptor

var file_agents_v1_daemon_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xd0, 0x02, 0x0a, 0x0a, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x2a, 0x0a, 0x11, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x70, 0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x70, 0x52, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x1a, 0x39, 0x0a, 0x0b, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0xad, 0x03, 0x0a, 0x0a, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x54, 0x61,
	0x73, 0x6b, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a,
	0x11, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x70,
	0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x63, 0x70, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x6f,
	0x72, 0x6b, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f,
	0x72, 0x6b, 0x44, 0x69, 0x72, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x4a, 0x04, 0x08, 0x07, 0x10, 0x08, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x22, 0x87, 0x02, 0x0a, 0x10, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x54,
	0x61, 0x73, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x65, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0x25,
	0x0a, 0x0a, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x56, 0x0a, 0x25, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d,
	0x0a, 0x06, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x22, 0x57, 0x0a,
	0x26, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x22, 0x61, 0x0a, 0x21, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0c, 0x77,
	0x61, 0x69, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x77, 0x61,
	0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x5c, 0x0a, 0x22, 0x44, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x36, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x64, 0x0a, 0x2d, 0x44, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x30, 0x0a,
	0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x29, 0x0a, 0x27, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x28, 0x44, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x3e,
	0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x36,
	0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0xb2, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x00, 0x52, 0x04, 0x74, 0x61,
	0x73, 0x6b, 0x12, 0x2f, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x00, 0x52, 0x06, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x12, 0x36, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00,
	0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0xda, 0x01, 0x0a, 0x10, 0x44, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x1e, 0x44,
	0x41, 0x45, 0x4d, 0x4f, 0x4e, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x1f, 0x0a, 0x1b, 0x44, 0x41, 0x45, 0x4d, 0x4f, 0x4e, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x1e, 0x0a, 0x1a, 0x44, 0x41, 0x45, 0x4d, 0x4f, 0x4e, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02,
	0x12, 0x20, 0x0a, 0x1c, 0x44, 0x41, 0x45, 0x4d, 0x4f, 0x4e, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44,
	0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19, 0x44, 0x41, 0x45, 0x4d, 0x4f, 0x4e, 0x5f, 0x54, 0x41, 0x53,
	0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10,
	0x04, 0x12, 0x20, 0x0a, 0x1c, 0x44, 0x41, 0x45, 0x4d, 0x4f, 0x4e, 0x5f, 0x54, 0x41, 0x53, 0x4b,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45,
	0x44, 0x10, 0x05, 0x32, 0xb5, 0x04, 0x0a, 0x16, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x19, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x30, 0x01, 0x12, 0x6f, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x30, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x04, 0x50, 0x6f, 0x6c, 0x6c, 0x12, 0x2c, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x87, 0x01, 0x0a, 0x10, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x38, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x75, 0x0a, 0x0a, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x32, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67,
	0x6f, 0x2e, 0x6f, 0x72, 0x78, 0x2e, 0x6d, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x75,
	0x74, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agents_v1_daemon_proto_rawDescOnce sync.Once
	file_agents_v1_daemon_proto_rawDescData = file_agents_v1_daemon_proto_rawDesc
)

func file_agents_v1_daemon_proto_rawDescGZIP() []byte {
	file_agents_v1_daemon_proto_rawDescOnce.Do(func() {
		file_agents_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_agents_v1_daemon_proto_rawDescData)
	})
	return file_agents_v1_daemon_proto_rawDescData
}

var file_agents_v1_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agents_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_agents_v1_daemon_proto_goTypes = []interface{}{
	(DaemonTaskStatus)(0),                                  // 0: agents.v1.DaemonTaskStatus
	(*DaemonInfo)(nil),                                     // 1: agents.v1.DaemonInfo
	(*DaemonTask)(nil),                                     // 2: agents.v1.DaemonTask
	(*DaemonTaskUpdate)(nil),                               // 3: agents.v1.DaemonTaskUpdate
	(*CancelTask)(nil),                                     // 4: agents.v1.CancelTask
	(*DaemonConnectorServiceRegisterRequest)(nil),          // 5: agents.v1.DaemonConnectorServiceRegisterRequest
	(*DaemonConnectorServiceRegisterResponse)(nil),         // 6: agents.v1.DaemonConnectorServiceRegisterResponse
	(*DaemonConnectorServicePollRequest)(nil),              // 7: agents.v1.DaemonConnectorServicePollRequest
	(*DaemonConnectorServicePollResponse)(nil),             // 8: agents.v1.DaemonConnectorServicePollResponse
	(*DaemonConnectorServiceReportTaskUpdateRequest)(nil),  // 9: agents.v1.DaemonConnectorServiceReportTaskUpdateRequest
	(*DaemonConnectorServiceReportTaskUpdateResponse)(nil), // 10: agents.v1.DaemonConnectorServiceReportTaskUpdateResponse
	(*DaemonConnectorServiceUnregisterRequest)(nil),        // 11: agents.v1.DaemonConnectorServiceUnregisterRequest
	(*DaemonConnectorServiceUnregisterResponse)(nil),       // 12: agents.v1.DaemonConnectorServiceUnregisterResponse
	(*ConnectRequest)(nil),                                 // 13: agents.v1.ConnectRequest
	(*ConnectResponse)(nil),                                // 14: agents.v1.ConnectResponse
	nil,                                                    // 15: agents.v1.DaemonInfo.LabelsEntry
	nil,                                                    // 16: agents.v1.DaemonTask.MetadataEntry
	(*timestamppb.Timestamp)(nil),                          // 17: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                            // 18: google.protobuf.Duration
	(*emptypb.Empty)(nil),                                  // 19: google.protobuf.Empty
}
var file_agents_v1_daemon_proto_depIdxs = []int32{
	15, // 0: agents.v1.DaemonInfo.labels:type_name -> agents.v1.DaemonInfo.LabelsEntry
	16, // 1: agents.v1.DaemonTask.metadata:type_name -> agents.v1.DaemonTask.MetadataEntry
	0,  // 2: agents.v1.DaemonTaskUpdate.status:type_name -> agents.v1.DaemonTaskStatus
	17, // 3: agents.v1.DaemonTaskUpdate.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 4: agents.v1.DaemonConnectorServiceRegisterRequest.daemon:type_name -> agents.v1.DaemonInfo
	1,  // 5: agents.v1.DaemonConnectorServiceRegisterResponse.daemon:type_name -> agents.v1.DaemonInfo
	18, // 6: agents.v1.DaemonConnectorServicePollRequest.wait_timeout:type_name -> google.protobuf.Duration
	14, // 7: agents.v1.DaemonConnectorServicePollResponse.messages:type_name -> agents.v1.ConnectResponse
	3,  // 8: agents.v1.DaemonConnectorServiceReportTaskUpdateRequest.update:type_name -> agents.v1.DaemonTaskUpdate
	1,  // 9: agents.v1.ConnectRequest.register:type_name -> agents.v1.DaemonInfo
	3,  // 10: agents.v1.ConnectRequest.task_update:type_name -> agents.v1.DaemonTaskUpdate
	19, // 11: agents.v1.ConnectRequest.heartbeat:type_name -> google.protobuf.Empty
	2,  // 12: agents.v1.ConnectResponse.task:type_name -> agents.v1.DaemonTask
	4,  // 13: agents.v1.ConnectResponse.cancel:type_name -> agents.v1.CancelTask
	19, // 14: agents.v1.ConnectResponse.heartbeat:type_name -> google.protobuf.Empty
	13, // 15: agents.v1.DaemonConnectorService.Connect:input_type -> agents.v1.ConnectRequest
	5,  // 16: agents.v1.DaemonConnectorService.Register:input_type -> agents.v1.DaemonConnectorServiceRegisterRequest
	7,  // 17: agents.v1.DaemonConnectorService.Poll:input_type -> agents.v1.DaemonConnectorServicePollRequest
	9,  // 18: agents.v1.DaemonConnectorService.ReportTaskUpdate:input_type -> agents.v1.DaemonConnectorServiceReportTaskUpdateRequest
	11, // 19: agents.v1.DaemonConnectorService.Unregister:input_type -> agents.v1.DaemonConnectorServiceUnregisterRequest
	14, // 20: agents.v1.DaemonConnectorService.Connect:output_type -> agents.v1.ConnectResponse
	6,  // 21: agents.v1.DaemonConnectorService.Register:output_type -> agents.v1.DaemonConnectorServiceRegisterResponse
	8,  // 22: agents.v1.DaemonConnectorService.Poll:output_type -> agents.v1.DaemonConnectorServicePollResponse
	10, // 23: agents.v1.DaemonConnectorService.ReportTaskUpdate:output_type -> agents.v1.DaemonConnectorServiceReportTaskUpdateResponse
	12, // 24: agents.v1.DaemonConnectorService.Unregister:output_type -> agents.v1.DaemonConnectorServiceUnregisterResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_agents_v1_daemon_proto_init() }
func file_agents_v1_daemon_proto_init() {
	if File_agents_v1_daemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agents_v1_daemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonTaskUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConnectorServiceRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConnectorServiceRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConnectorServicePollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConnectorServicePollResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConnectorServiceReportTaskUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConnectorServiceReportTaskUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConnectorServiceUnregisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConnectorServiceUnregisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_v1_daemon_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_agents_v1_daemon_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ConnectRequest_Register)(nil),
		(*ConnectRequest_TaskUpdate)(nil),
		(*ConnectRequest_Heartbeat)(nil),
	}
	file_agents_v1_daemon_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*ConnectResponse_Task)(nil),
		(*ConnectResponse_Cancel)(nil),
		(*ConnectResponse_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agents_v1_daemon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agents_v1_daemon_proto_goTypes,
		DependencyIndexes: file_agents_v1_daemon_proto_depIdxs,
		EnumInfos:         file_agents_v1_daemon_proto_enumTypes,
		MessageInfos:      file_agents_v1_daemon_proto_msgTypes,
	}.Build()
	File_agents_v1_daemon_proto = out.File
	file_agents_v1_daemon_proto_rawDesc = nil
	file_agents_v1_daemon_proto_goTypes = nil
	file_agents_v1_daemon_proto_depIdxs = nil
}
