// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: agents/v1/forum.proto

package agentsv1

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ======================
// ForumService Interface
// ======================

// ForumService manages workspace-scoped discussion threads where users and
// agents can participate together.
type ForumService interface {
	ListThreads(context.Context, *ListForumThreadsRequest) (*ListForumThreadsResponse, error)

	GetThread(context.Context, *GetForumThreadRequest) (*GetForumThreadResponse, error)

	CreateThread(context.Context, *CreateForumThreadRequest) (*CreateForumThreadResponse, error)

	UpdateThread(context.Context, *UpdateForumThreadRequest) (*UpdateForumThreadResponse, error)

	DeleteThread(context.Context, *DeleteForumThreadRequest) (*DeleteForumThreadResponse, error)

	CreatePost(context.Context, *CreateForumPostRequest) (*CreateForumPostResponse, error)

	DeletePost(context.Context, *DeleteForumPostRequest) (*DeleteForumPostResponse, error)

	InvokeAgentInThread(context.Context, *InvokeAgentInThreadRequest) (*InvokeAgentInThreadResponse, error)
}

// ============================
// ForumService Protobuf Client
// ============================

type forumServiceProtobufClient struct {
	client      HTTPClient
	urls        [8]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewForumServiceProtobufClient creates a Protobuf client that implements the ForumService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewForumServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) ForumService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "agents.v1", "ForumService")
	urls := [8]string{
		serviceURL + "ListThreads",
		serviceURL + "GetThread",
		serviceURL + "CreateThread",
		serviceURL + "UpdateThread",
		serviceURL + "DeleteThread",
		serviceURL + "CreatePost",
		serviceURL + "DeletePost",
		serviceURL + "InvokeAgentInThread",
	}

	return &forumServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *forumServiceProtobufClient) ListThreads(ctx context.Context, in *ListForumThreadsRequest) (*ListForumThreadsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "ListThreads")
	caller := c.callListThreads
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListForumThreadsRequest) (*ListForumThreadsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListForumThreadsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListForumThreadsRequest) when calling interceptor")
					}
					return c.callListThreads(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListForumThreadsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListForumThreadsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceProtobufClient) callListThreads(ctx context.Context, in *ListForumThreadsRequest) (*ListForumThreadsResponse, error) {
	out := new(ListForumThreadsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceProtobufClient) GetThread(ctx context.Context, in *GetForumThreadRequest) (*GetForumThreadResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "GetThread")
	caller := c.callGetThread
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetForumThreadRequest) (*GetForumThreadResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetForumThreadRequest) when calling interceptor")
					}
					return c.callGetThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceProtobufClient) callGetThread(ctx context.Context, in *GetForumThreadRequest) (*GetForumThreadResponse, error) {
	out := new(GetForumThreadResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceProtobufClient) CreateThread(ctx context.Context, in *CreateForumThreadRequest) (*CreateForumThreadResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateThread")
	caller := c.callCreateThread
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateForumThreadRequest) (*CreateForumThreadResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateForumThreadRequest) when calling interceptor")
					}
					return c.callCreateThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceProtobufClient) callCreateThread(ctx context.Context, in *CreateForumThreadRequest) (*CreateForumThreadResponse, error) {
	out := new(CreateForumThreadResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceProtobufClient) UpdateThread(ctx context.Context, in *UpdateForumThreadRequest) (*UpdateForumThreadResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateThread")
	caller := c.callUpdateThread
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateForumThreadRequest) (*UpdateForumThreadResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateForumThreadRequest) when calling interceptor")
					}
					return c.callUpdateThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdateForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdateForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceProtobufClient) callUpdateThread(ctx context.Context, in *UpdateForumThreadRequest) (*UpdateForumThreadResponse, error) {
	out := new(UpdateForumThreadResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceProtobufClient) DeleteThread(ctx context.Context, in *DeleteForumThreadRequest) (*DeleteForumThreadResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteThread")
	caller := c.callDeleteThread
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteForumThreadRequest) (*DeleteForumThreadResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteForumThreadRequest) when calling interceptor")
					}
					return c.callDeleteThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceProtobufClient) callDeleteThread(ctx context.Context, in *DeleteForumThreadRequest) (*DeleteForumThreadResponse, error) {
	out := new(DeleteForumThreadResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceProtobufClient) CreatePost(ctx context.Context, in *CreateForumPostRequest) (*CreateForumPostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	caller := c.callCreatePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateForumPostRequest) (*CreateForumPostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateForumPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateForumPostRequest) when calling interceptor")
					}
					return c.callCreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateForumPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateForumPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceProtobufClient) callCreatePost(ctx context.Context, in *CreateForumPostRequest) (*CreateForumPostResponse, error) {
	out := new(CreateForumPostResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[5], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceProtobufClient) DeletePost(ctx context.Context, in *DeleteForumPostRequest) (*DeleteForumPostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	caller := c.callDeletePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteForumPostRequest) (*DeleteForumPostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteForumPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteForumPostRequest) when calling interceptor")
					}
					return c.callDeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteForumPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteForumPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceProtobufClient) callDeletePost(ctx context.Context, in *DeleteForumPostRequest) (*DeleteForumPostResponse, error) {
	out := new(DeleteForumPostResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[6], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceProtobufClient) InvokeAgentInThread(ctx context.Context, in *InvokeAgentInThreadRequest) (*InvokeAgentInThreadResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "InvokeAgentInThread")
	caller := c.callInvokeAgentInThread
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *InvokeAgentInThreadRequest) (*InvokeAgentInThreadResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*InvokeAgentInThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*InvokeAgentInThreadRequest) when calling interceptor")
					}
					return c.callInvokeAgentInThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*InvokeAgentInThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*InvokeAgentInThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceProtobufClient) callInvokeAgentInThread(ctx context.Context, in *InvokeAgentInThreadRequest) (*InvokeAgentInThreadResponse, error) {
	out := new(InvokeAgentInThreadResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[7], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ========================
// ForumService JSON Client
// ========================

type forumServiceJSONClient struct {
	client      HTTPClient
	urls        [8]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewForumServiceJSONClient creates a JSON client that implements the ForumService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewForumServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) ForumService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "agents.v1", "ForumService")
	urls := [8]string{
		serviceURL + "ListThreads",
		serviceURL + "GetThread",
		serviceURL + "CreateThread",
		serviceURL + "UpdateThread",
		serviceURL + "DeleteThread",
		serviceURL + "CreatePost",
		serviceURL + "DeletePost",
		serviceURL + "InvokeAgentInThread",
	}

	return &forumServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *forumServiceJSONClient) ListThreads(ctx context.Context, in *ListForumThreadsRequest) (*ListForumThreadsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "ListThreads")
	caller := c.callListThreads
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListForumThreadsRequest) (*ListForumThreadsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListForumThreadsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListForumThreadsRequest) when calling interceptor")
					}
					return c.callListThreads(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListForumThreadsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListForumThreadsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceJSONClient) callListThreads(ctx context.Context, in *ListForumThreadsRequest) (*ListForumThreadsResponse, error) {
	out := new(ListForumThreadsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceJSONClient) GetThread(ctx context.Context, in *GetForumThreadRequest) (*GetForumThreadResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "GetThread")
	caller := c.callGetThread
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetForumThreadRequest) (*GetForumThreadResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetForumThreadRequest) when calling interceptor")
					}
					return c.callGetThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceJSONClient) callGetThread(ctx context.Context, in *GetForumThreadRequest) (*GetForumThreadResponse, error) {
	out := new(GetForumThreadResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceJSONClient) CreateThread(ctx context.Context, in *CreateForumThreadRequest) (*CreateForumThreadResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateThread")
	caller := c.callCreateThread
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateForumThreadRequest) (*CreateForumThreadResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateForumThreadRequest) when calling interceptor")
					}
					return c.callCreateThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceJSONClient) callCreateThread(ctx context.Context, in *CreateForumThreadRequest) (*CreateForumThreadResponse, error) {
	out := new(CreateForumThreadResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceJSONClient) UpdateThread(ctx context.Context, in *UpdateForumThreadRequest) (*UpdateForumThreadResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateThread")
	caller := c.callUpdateThread
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateForumThreadRequest) (*UpdateForumThreadResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateForumThreadRequest) when calling interceptor")
					}
					return c.callUpdateThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdateForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdateForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceJSONClient) callUpdateThread(ctx context.Context, in *UpdateForumThreadRequest) (*UpdateForumThreadResponse, error) {
	out := new(UpdateForumThreadResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceJSONClient) DeleteThread(ctx context.Context, in *DeleteForumThreadRequest) (*DeleteForumThreadResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteThread")
	caller := c.callDeleteThread
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteForumThreadRequest) (*DeleteForumThreadResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteForumThreadRequest) when calling interceptor")
					}
					return c.callDeleteThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceJSONClient) callDeleteThread(ctx context.Context, in *DeleteForumThreadRequest) (*DeleteForumThreadResponse, error) {
	out := new(DeleteForumThreadResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceJSONClient) CreatePost(ctx context.Context, in *CreateForumPostRequest) (*CreateForumPostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	caller := c.callCreatePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateForumPostRequest) (*CreateForumPostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateForumPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateForumPostRequest) when calling interceptor")
					}
					return c.callCreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateForumPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateForumPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceJSONClient) callCreatePost(ctx context.Context, in *CreateForumPostRequest) (*CreateForumPostResponse, error) {
	out := new(CreateForumPostResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[5], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceJSONClient) DeletePost(ctx context.Context, in *DeleteForumPostRequest) (*DeleteForumPostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	caller := c.callDeletePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteForumPostRequest) (*DeleteForumPostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteForumPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteForumPostRequest) when calling interceptor")
					}
					return c.callDeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteForumPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteForumPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceJSONClient) callDeletePost(ctx context.Context, in *DeleteForumPostRequest) (*DeleteForumPostResponse, error) {
	out := new(DeleteForumPostResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[6], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *forumServiceJSONClient) InvokeAgentInThread(ctx context.Context, in *InvokeAgentInThreadRequest) (*InvokeAgentInThreadResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithMethodName(ctx, "InvokeAgentInThread")
	caller := c.callInvokeAgentInThread
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *InvokeAgentInThreadRequest) (*InvokeAgentInThreadResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*InvokeAgentInThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*InvokeAgentInThreadRequest) when calling interceptor")
					}
					return c.callInvokeAgentInThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*InvokeAgentInThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*InvokeAgentInThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *forumServiceJSONClient) callInvokeAgentInThread(ctx context.Context, in *InvokeAgentInThreadRequest) (*InvokeAgentInThreadResponse, error) {
	out := new(InvokeAgentInThreadResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[7], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===========================
// ForumService Server Handler
// ===========================

type forumServiceServer struct {
	ForumService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewForumServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewForumServiceServer(svc ForumService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &forumServiceServer{
		ForumService:     svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *forumServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *forumServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// ForumServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const ForumServicePathPrefix = "/twirp/agents.v1.ForumService/"

func (s *forumServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "agents.v1")
	ctx = ctxsetters.WithServiceName(ctx, "ForumService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "agents.v1.ForumService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "ListThreads":
		s.serveListThreads(ctx, resp, req)
		return
	case "GetThread":
		s.serveGetThread(ctx, resp, req)
		return
	case "CreateThread":
		s.serveCreateThread(ctx, resp, req)
		return
	case "UpdateThread":
		s.serveUpdateThread(ctx, resp, req)
		return
	case "DeleteThread":
		s.serveDeleteThread(ctx, resp, req)
		return
	case "CreatePost":
		s.serveCreatePost(ctx, resp, req)
		return
	case "DeletePost":
		s.serveDeletePost(ctx, resp, req)
		return
	case "InvokeAgentInThread":
		s.serveInvokeAgentInThread(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *forumServiceServer) serveListThreads(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListThreadsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListThreadsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *forumServiceServer) serveListThreadsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListThreads")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListForumThreadsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ForumService.ListThreads
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListForumThreadsRequest) (*ListForumThreadsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListForumThreadsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListForumThreadsRequest) when calling interceptor")
					}
					return s.ForumService.ListThreads(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListForumThreadsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListForumThreadsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListForumThreadsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListForumThreadsResponse and nil error while calling ListThreads. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveListThreadsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListThreads")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListForumThreadsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ForumService.ListThreads
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListForumThreadsRequest) (*ListForumThreadsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListForumThreadsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListForumThreadsRequest) when calling interceptor")
					}
					return s.ForumService.ListThreads(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListForumThreadsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListForumThreadsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListForumThreadsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListForumThreadsResponse and nil error while calling ListThreads. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveGetThread(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetThreadJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetThreadProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *forumServiceServer) serveGetThreadJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetThread")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetForumThreadRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ForumService.GetThread
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetForumThreadRequest) (*GetForumThreadResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetForumThreadRequest) when calling interceptor")
					}
					return s.ForumService.GetThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetForumThreadResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetForumThreadResponse and nil error while calling GetThread. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveGetThreadProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetThread")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetForumThreadRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ForumService.GetThread
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetForumThreadRequest) (*GetForumThreadResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetForumThreadRequest) when calling interceptor")
					}
					return s.ForumService.GetThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetForumThreadResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetForumThreadResponse and nil error while calling GetThread. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveCreateThread(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreateThreadJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreateThreadProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *forumServiceServer) serveCreateThreadJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateThread")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CreateForumThreadRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ForumService.CreateThread
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateForumThreadRequest) (*CreateForumThreadResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateForumThreadRequest) when calling interceptor")
					}
					return s.ForumService.CreateThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreateForumThreadResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreateForumThreadResponse and nil error while calling CreateThread. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveCreateThreadProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateThread")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CreateForumThreadRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ForumService.CreateThread
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateForumThreadRequest) (*CreateForumThreadResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateForumThreadRequest) when calling interceptor")
					}
					return s.ForumService.CreateThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreateForumThreadResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreateForumThreadResponse and nil error while calling CreateThread. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveUpdateThread(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUpdateThreadJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUpdateThreadProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *forumServiceServer) serveUpdateThreadJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateThread")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UpdateForumThreadRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ForumService.UpdateThread
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateForumThreadRequest) (*UpdateForumThreadResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateForumThreadRequest) when calling interceptor")
					}
					return s.ForumService.UpdateThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdateForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdateForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *UpdateForumThreadResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UpdateForumThreadResponse and nil error while calling UpdateThread. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveUpdateThreadProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateThread")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UpdateForumThreadRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ForumService.UpdateThread
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateForumThreadRequest) (*UpdateForumThreadResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateForumThreadRequest) when calling interceptor")
					}
					return s.ForumService.UpdateThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdateForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdateForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *UpdateForumThreadResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UpdateForumThreadResponse and nil error while calling UpdateThread. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveDeleteThread(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeleteThreadJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeleteThreadProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *forumServiceServer) serveDeleteThreadJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteThread")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeleteForumThreadRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ForumService.DeleteThread
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteForumThreadRequest) (*DeleteForumThreadResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteForumThreadRequest) when calling interceptor")
					}
					return s.ForumService.DeleteThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeleteForumThreadResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteForumThreadResponse and nil error while calling DeleteThread. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveDeleteThreadProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteThread")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeleteForumThreadRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ForumService.DeleteThread
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteForumThreadRequest) (*DeleteForumThreadResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteForumThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteForumThreadRequest) when calling interceptor")
					}
					return s.ForumService.DeleteThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteForumThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteForumThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeleteForumThreadResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteForumThreadResponse and nil error while calling DeleteThread. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveCreatePost(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreatePostJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreatePostProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *forumServiceServer) serveCreatePostJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CreateForumPostRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ForumService.CreatePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateForumPostRequest) (*CreateForumPostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateForumPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateForumPostRequest) when calling interceptor")
					}
					return s.ForumService.CreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateForumPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateForumPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreateForumPostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreateForumPostResponse and nil error while calling CreatePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveCreatePostProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CreateForumPostRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ForumService.CreatePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateForumPostRequest) (*CreateForumPostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateForumPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateForumPostRequest) when calling interceptor")
					}
					return s.ForumService.CreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateForumPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateForumPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreateForumPostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreateForumPostResponse and nil error while calling CreatePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveDeletePost(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeletePostJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeletePostProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *forumServiceServer) serveDeletePostJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeleteForumPostRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ForumService.DeletePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteForumPostRequest) (*DeleteForumPostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteForumPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteForumPostRequest) when calling interceptor")
					}
					return s.ForumService.DeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteForumPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteForumPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeleteForumPostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteForumPostResponse and nil error while calling DeletePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveDeletePostProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeleteForumPostRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ForumService.DeletePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteForumPostRequest) (*DeleteForumPostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteForumPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteForumPostRequest) when calling interceptor")
					}
					return s.ForumService.DeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteForumPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteForumPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeleteForumPostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteForumPostResponse and nil error while calling DeletePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveInvokeAgentInThread(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveInvokeAgentInThreadJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveInvokeAgentInThreadProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *forumServiceServer) serveInvokeAgentInThreadJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "InvokeAgentInThread")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(InvokeAgentInThreadRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.ForumService.InvokeAgentInThread
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *InvokeAgentInThreadRequest) (*InvokeAgentInThreadResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*InvokeAgentInThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*InvokeAgentInThreadRequest) when calling interceptor")
					}
					return s.ForumService.InvokeAgentInThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*InvokeAgentInThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*InvokeAgentInThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *InvokeAgentInThreadResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *InvokeAgentInThreadResponse and nil error while calling InvokeAgentInThread. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) serveInvokeAgentInThreadProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "InvokeAgentInThread")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(InvokeAgentInThreadRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.ForumService.InvokeAgentInThread
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *InvokeAgentInThreadRequest) (*InvokeAgentInThreadResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*InvokeAgentInThreadRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*InvokeAgentInThreadRequest) when calling interceptor")
					}
					return s.ForumService.InvokeAgentInThread(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*InvokeAgentInThreadResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*InvokeAgentInThreadResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *InvokeAgentInThreadResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *InvokeAgentInThreadResponse and nil error while calling InvokeAgentInThread. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *forumServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor7, 0
}

func (s *forumServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *forumServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "agents.v1", "ForumService")
}

var twirpFileDescriptor7 = []byte{
	// 1143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdb, 0x72, 0xdb, 0x44,
	0x18, 0x1e, 0xf9, 0x14, 0xeb, 0xb7, 0xd3, 0xd0, 0x25, 0x75, 0x14, 0x65, 0x3a, 0x75, 0x94, 0x34,
	0xe3, 0xc9, 0x85, 0x4c, 0x52, 0x2e, 0x80, 0xde, 0x90, 0x16, 0xe8, 0x78, 0x7a, 0x20, 0xe3, 0xa4,
	0xcc, 0x94, 0x1b, 0x8f, 0x6c, 0x6d, 0x5c, 0x8d, 0x2d, 0xad, 0xd0, 0xae, 0x4c, 0xdd, 0x2b, 0xae,
	0x79, 0x03, 0xae, 0x79, 0x08, 0x5e, 0x00, 0x1e, 0x82, 0xc7, 0xe0, 0x0d, 0x98, 0x3d, 0xc8, 0x96,
	0x6d, 0xc9, 0x35, 0x01, 0xee, 0xbc, 0xff, 0x7e, 0xfb, 0x9f, 0xbe, 0xff, 0x20, 0xc3, 0x3d, 0x67,
	0x88, 0x03, 0x46, 0xdb, 0x93, 0xb3, 0xf6, 0x0d, 0x89, 0x62, 0xdf, 0x0e, 0x23, 0xc2, 0x08, 0xd2,
	0xa5, 0xd8, 0x9e, 0x9c, 0x99, 0x0f, 0x86, 0x84, 0x0c, 0xc7, 0xb8, 0x2d, 0x2e, 0xfa, 0xf1, 0x4d,
	0x9b, 0x79, 0x3e, 0xa6, 0xcc, 0xf1, 0x43, 0x89, 0xb5, 0x7e, 0x2b, 0x42, 0xed, 0x1b, 0xfe, 0xf6,
	0xfa, 0x6d, 0x84, 0x1d, 0x17, 0xdd, 0x81, 0x82, 0xe7, 0x1a, 0x5a, 0x53, 0x6b, 0xe9, 0xdd, 0x82,
	0xe7, 0xa2, 0x5d, 0x28, 0x33, 0x8f, 0x8d, 0xb1, 0x51, 0x10, 0x22, 0x79, 0x40, 0x08, 0x4a, 0x7d,
	0xe2, 0x4e, 0x8d, 0xa2, 0x10, 0x8a, 0xdf, 0xe8, 0x3e, 0xc0, 0x20, 0xc2, 0x0e, 0xc3, 0x6e, 0xaf,
	0x3f, 0x35, 0x4a, 0xe2, 0x46, 0x57, 0x92, 0x27, 0x53, 0xd4, 0x80, 0x0a, 0x65, 0x0e, 0x8b, 0xa9,
	0x51, 0x16, 0x57, 0xea, 0x84, 0x1e, 0x40, 0x4d, 0xb8, 0xdb, 0x0b, 0x1c, 0x1f, 0x53, 0xa3, 0xd2,
	0x2c, 0xb6, 0xf4, 0x2e, 0x08, 0xd1, 0x2b, 0x2e, 0x41, 0x5f, 0x42, 0xd5, 0xc7, 0xcc, 0x71, 0x1d,
	0xe6, 0x18, 0x5b, 0xcd, 0x62, 0xab, 0x76, 0x7e, 0x6c, 0xcf, 0x02, 0xb4, 0x53, 0xbe, 0xdb, 0x2f,
	0x15, 0xec, 0xeb, 0x80, 0x45, 0xd3, 0xee, 0xec, 0x15, 0xfa, 0x7c, 0xee, 0x99, 0xc3, 0x8c, 0x6a,
	0x53, 0x6b, 0xd5, 0xce, 0x4d, 0x5b, 0x66, 0xc6, 0x4e, 0x32, 0x63, 0x5f, 0x27, 0x99, 0x99, 0x79,
	0x7d, 0xc1, 0xf8, 0xd3, 0x38, 0x74, 0x93, 0xa7, 0xfa, 0x87, 0x9f, 0x2a, 0xf4, 0x05, 0x43, 0x87,
	0x50, 0xff, 0x91, 0x44, 0x23, 0x1a, 0x3a, 0x03, 0xdc, 0xf3, 0x5c, 0xc3, 0x15, 0x61, 0xd7, 0x66,
	0xb2, 0x8e, 0x6b, 0x3e, 0x86, 0xed, 0x05, 0x9f, 0xd1, 0x47, 0x50, 0x1c, 0xe1, 0xa9, 0x4a, 0x3f,
	0xff, 0xc9, 0xf3, 0x3f, 0x71, 0xc6, 0xf1, 0x2c, 0xff, 0xe2, 0xf0, 0x45, 0xe1, 0x33, 0xcd, 0xfa,
	0xb5, 0x08, 0xba, 0x88, 0xfe, 0x92, 0x50, 0xb6, 0xc2, 0xdb, 0x01, 0xe8, 0x4c, 0x64, 0x85, 0x9b,
	0x96, 0x6f, 0xab, 0x52, 0xd0, 0x71, 0x33, 0xe9, 0x3b, 0x86, 0x3b, 0x4e, 0xcc, 0xde, 0x92, 0xa8,
	0x17, 0x53, 0x1c, 0xf1, 0x57, 0x92, 0xc2, 0xba, 0x94, 0xbe, 0xa6, 0x38, 0xea, 0xb8, 0xe8, 0x14,
	0xee, 0x2a, 0xd4, 0x9c, 0x34, 0x45, 0xe8, 0x8e, 0xbc, 0xb8, 0x48, 0x98, 0x13, 0xcc, 0x4a, 0xec,
	0xc8, 0x0b, 0x5c, 0xa3, 0x22, 0x50, 0x20, 0x45, 0xcf, 0xbd, 0xc0, 0x45, 0x47, 0xb0, 0xed, 0x05,
	0x13, 0x32, 0x70, 0x98, 0x47, 0x02, 0x6e, 0x71, 0x4b, 0x5a, 0x9c, 0x0b, 0x3b, 0x2e, 0xf7, 0x2b,
	0x74, 0x22, 0x6e, 0x2b, 0x24, 0x94, 0x71, 0x54, 0x55, 0xa2, 0xa4, 0x94, 0x07, 0xdf, 0x71, 0x97,
	0x28, 0xd6, 0x6f, 0x4f, 0x31, 0xfc, 0xb7, 0x14, 0x5b, 0x3e, 0xec, 0xbd, 0xf0, 0x28, 0x4b, 0x95,
	0x29, 0xed, 0xe2, 0x1f, 0x62, 0x4c, 0x59, 0xaa, 0x23, 0xb4, 0x85, 0x8e, 0x38, 0x00, 0x3d, 0x74,
	0x86, 0xb8, 0x47, 0xbd, 0xf7, 0x92, 0xf6, 0x72, 0xb7, 0xca, 0x05, 0x57, 0xde, 0x7b, 0xcc, 0xbb,
	0x4c, 0x5c, 0x32, 0x32, 0xc2, 0x81, 0x22, 0x50, 0xc0, 0xaf, 0xb9, 0xc0, 0xfa, 0x59, 0x03, 0x63,
	0xd5, 0x1e, 0x0d, 0x49, 0x40, 0x31, 0xfa, 0x04, 0xb6, 0x64, 0x09, 0x70, 0x8b, 0xbc, 0x91, 0x1a,
	0xd9, 0x8d, 0xd4, 0x4d, 0x60, 0xe8, 0x04, 0x76, 0x02, 0xfc, 0x8e, 0xf5, 0x52, 0x26, 0x65, 0x2d,
	0x6d, 0x73, 0xf1, 0x65, 0x62, 0x56, 0x4c, 0x09, 0xc2, 0x9c, 0xb1, 0x70, 0xa8, 0xdc, 0x95, 0x07,
	0x2b, 0x86, 0x7b, 0xcf, 0x70, 0xda, 0x95, 0x24, 0xf2, 0xe5, 0x62, 0xe5, 0x1c, 0x73, 0x72, 0x97,
	0xc3, 0xae, 0x73, 0xe9, 0x65, 0x12, 0xfa, 0x09, 0xec, 0xcc, 0x51, 0xe9, 0xf8, 0xb7, 0x13, 0x98,
	0xcc, 0xc1, 0xef, 0x1a, 0x34, 0x96, 0xed, 0xaa, 0x0c, 0xd8, 0x50, 0x91, 0xa1, 0x09, 0xe3, 0xf9,
	0x09, 0x50, 0x28, 0x74, 0x0a, 0x65, 0xae, 0x9b, 0x1a, 0x05, 0x91, 0xaf, 0xdd, 0x65, 0x38, 0xaf,
	0xbe, 0xae, 0x84, 0xa0, 0x36, 0xec, 0xca, 0x5c, 0x65, 0xfa, 0x78, 0x57, 0x24, 0x2c, 0xed, 0xa7,
	0xa0, 0x92, 0x63, 0x65, 0xe6, 0x4a, 0x22, 0x62, 0x9d, 0x4b, 0xae, 0x45, 0xf6, 0xfe, 0xd2, 0xc0,
	0x78, 0x2a, 0xaa, 0x34, 0x23, 0x83, 0xb3, 0xb1, 0xac, 0x65, 0x8d, 0xe5, 0x42, 0xaa, 0xaf, 0x97,
	0xe6, 0x6b, 0x71, 0x65, 0xbe, 0xbe, 0x4c, 0xcd, 0xd7, 0x92, 0x08, 0xf3, 0x2c, 0x15, 0x66, 0x9e,
	0x07, 0x79, 0xc3, 0xf6, 0xdf, 0xcd, 0xb4, 0x9f, 0x34, 0xd8, 0xcf, 0xb0, 0x78, 0x4b, 0xf6, 0x1e,
	0x01, 0xdc, 0x78, 0x11, 0x95, 0x94, 0x08, 0x63, 0x79, 0x14, 0xea, 0x02, 0xc7, 0x7f, 0x5a, 0xbf,
	0x14, 0xc0, 0x78, 0x2d, 0x3a, 0x7c, 0x83, 0xc2, 0xdd, 0x7c, 0x3b, 0xce, 0x9b, 0xbd, 0xb4, 0x6e,
	0xfd, 0x95, 0xd7, 0xd2, 0x53, 0x59, 0xa1, 0x27, 0xcf, 0xd3, 0xff, 0x87, 0x9e, 0xe7, 0xb0, 0x9f,
	0x61, 0xf0, 0x76, 0xec, 0x58, 0xa7, 0x60, 0x7c, 0x85, 0xc7, 0x78, 0x93, 0x3c, 0x5b, 0x07, 0xb0,
	0x9f, 0x81, 0x95, 0x86, 0x2d, 0x02, 0x8d, 0x54, 0xcd, 0x08, 0x3e, 0x95, 0x9a, 0x85, 0x25, 0xa8,
	0xe5, 0x2c, 0xc1, 0xc2, 0xe2, 0x12, 0x5c, 0x5a, 0x36, 0xc5, 0xd5, 0x65, 0x63, 0x3d, 0x85, 0xbd,
	0x15, 0x83, 0x2a, 0x09, 0x2d, 0x28, 0x89, 0x62, 0xd3, 0xd6, 0x14, 0x9b, 0x40, 0x58, 0xaf, 0xa0,
	0x91, 0x0a, 0x69, 0x63, 0xaf, 0xf7, 0x60, 0x2b, 0x71, 0x4d, 0x3a, 0x5e, 0x09, 0xa5, 0x53, 0xfb,
	0xb0, 0xb7, 0xa2, 0x4f, 0x25, 0xe8, 0x0f, 0x0d, 0xcc, 0x4e, 0x30, 0x21, 0x23, 0x2c, 0x96, 0x73,
	0x27, 0x58, 0x4c, 0xf6, 0x5a, 0x7b, 0xf7, 0x01, 0x52, 0x9b, 0x5e, 0x9a, 0xd4, 0x67, 0xe5, 0x89,
	0x0c, 0xd8, 0xf2, 0x31, 0xa5, 0xce, 0x10, 0xab, 0x4c, 0x25, 0x47, 0xf4, 0x10, 0xee, 0xf8, 0xc4,
	0xc5, 0xe3, 0x1e, 0x99, 0xe0, 0x28, 0xf2, 0x5c, 0xac, 0x0a, 0x7f, 0x5b, 0x48, 0xbf, 0x55, 0x42,
	0xfe, 0x41, 0x11, 0xe1, 0xc1, 0x2c, 0xe3, 0x63, 0xcf, 0xf7, 0x98, 0xf8, 0xa0, 0x28, 0x77, 0x77,
	0xe4, 0x05, 0x0f, 0xe5, 0x05, 0x17, 0x5b, 0x03, 0x38, 0xc8, 0x0c, 0xe3, 0x9f, 0xe6, 0x1e, 0x99,
	0x50, 0x8d, 0xd4, 0xab, 0xe4, 0xdb, 0x28, 0x39, 0x9f, 0xff, 0x59, 0x86, 0xba, 0xc0, 0x5f, 0xe1,
	0x68, 0xe2, 0x0d, 0x30, 0xfa, 0x0e, 0x6a, 0x7c, 0xa3, 0xaa, 0x65, 0x8a, 0xac, 0x94, 0xde, 0x9c,
	0xcd, 0x6e, 0x1e, 0xad, 0xc5, 0x28, 0x77, 0x2f, 0x41, 0x7f, 0x86, 0x95, 0x5a, 0xd4, 0x4c, 0xbd,
	0xc8, 0xdc, 0x99, 0xe6, 0xe1, 0x1a, 0x84, 0xd2, 0xf8, 0x06, 0xea, 0xb2, 0x2e, 0x95, 0xd2, 0xa3,
	0x0d, 0xe6, 0xb8, 0x79, 0xbc, 0x1e, 0x34, 0x57, 0x2d, 0x3b, 0x3f, 0x43, 0x75, 0xde, 0x0c, 0x5a,
	0x50, 0x9d, 0x3f, 0x37, 0xde, 0x40, 0x5d, 0x16, 0x6e, 0x86, 0xea, 0xbc, 0x01, 0xb1, 0xa0, 0x3a,
	0x77, 0x32, 0xa0, 0x2b, 0x00, 0x19, 0x92, 0xf8, 0x44, 0x3e, 0xcc, 0x8e, 0x34, 0xd5, 0x7a, 0xa6,
	0xb5, 0x0e, 0x32, 0x57, 0x2a, 0x2d, 0xae, 0x28, 0xcd, 0xee, 0xe7, 0x05, 0xa5, 0x39, 0x2d, 0x8a,
	0x5c, 0xf8, 0x38, 0xa3, 0xb4, 0xd1, 0xc3, 0xd4, 0xd3, 0xfc, 0x0e, 0x36, 0x4f, 0x3e, 0x04, 0x93,
	0x56, 0x9e, 0x7c, 0xfa, 0xfd, 0xf9, 0x90, 0xd8, 0x24, 0x7a, 0x67, 0xfb, 0xb8, 0xed, 0x84, 0x21,
	0x6d, 0xf7, 0x63, 0xc6, 0x70, 0xd4, 0x0e, 0x47, 0x43, 0xf9, 0x17, 0xb1, 0x3d, 0xfb, 0x47, 0xf9,
	0x58, 0xfe, 0x9a, 0x9c, 0xf5, 0x2b, 0xe2, 0xe6, 0xd1, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x10,
	0x43, 0x9d, 0x8e, 0x6e, 0x0e, 0x00, 0x00,
}
