// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agents/v1/repobinding.proto

package agentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspaceRepoBindingService_GetWorkspaceRepoBinding_FullMethodName           = "/agents.v1.WorkspaceRepoBindingService/GetWorkspaceRepoBinding"
	WorkspaceRepoBindingService_PutWorkspaceRepoBinding_FullMethodName           = "/agents.v1.WorkspaceRepoBindingService/PutWorkspaceRepoBinding"
	WorkspaceRepoBindingService_DeleteWorkspaceRepoBinding_FullMethodName        = "/agents.v1.WorkspaceRepoBindingService/DeleteWorkspaceRepoBinding"
	WorkspaceRepoBindingService_SetWorkspaceRepoBindingCredential_FullMethodName = "/agents.v1.WorkspaceRepoBindingService/SetWorkspaceRepoBindingCredential"
	WorkspaceRepoBindingService_ValidateWorkspaceRepoBinding_FullMethodName      = "/agents.v1.WorkspaceRepoBindingService/ValidateWorkspaceRepoBinding"
)

// WorkspaceRepoBindingServiceClient is the client API for WorkspaceRepoBindingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkspaceRepoBindingService manages the current workspace's repository
// binding. All RPCs derive the workspace from the X-Workspace-ID header.
// Get is available to every workspace member; the mutating RPCs require the
// caller to be a workspace owner or admin (global admins bypass).
type WorkspaceRepoBindingServiceClient interface {
	// GetWorkspaceRepoBinding returns the binding (unset when none exists)
	// plus any overlapping bindings in other workspaces. Never returns
	// credential material.
	GetWorkspaceRepoBinding(ctx context.Context, in *GetWorkspaceRepoBindingRequest, opts ...grpc.CallOption) (*GetWorkspaceRepoBindingResponse, error)
	// PutWorkspaceRepoBinding creates or replaces the workspace's binding
	// configuration. Server-owned fields (credential, status, timestamps) are
	// ignored on input. Every Put resets status to UNVALIDATED: each binding
	// field (including write mode) changes what validation must prove.
	PutWorkspaceRepoBinding(ctx context.Context, in *PutWorkspaceRepoBindingRequest, opts ...grpc.CallOption) (*PutWorkspaceRepoBindingResponse, error)
	// DeleteWorkspaceRepoBinding removes the binding and its stored credential.
	DeleteWorkspaceRepoBinding(ctx context.Context, in *DeleteWorkspaceRepoBindingRequest, opts ...grpc.CallOption) (*DeleteWorkspaceRepoBindingResponse, error)
	// SetWorkspaceRepoBindingCredential sets or replaces the binding's PAT.
	// The PAT is write-only: it is encrypted before storage and never returned.
	SetWorkspaceRepoBindingCredential(ctx context.Context, in *SetWorkspaceRepoBindingCredentialRequest, opts ...grpc.CallOption) (*SetWorkspaceRepoBindingCredentialResponse, error)
	// ValidateWorkspaceRepoBinding probes the repository with the stored
	// credential (visibility/read, branch existence, write capability, PR/MR
	// capability as required by the write mode), persists the outcome on the
	// binding, and returns it.
	ValidateWorkspaceRepoBinding(ctx context.Context, in *ValidateWorkspaceRepoBindingRequest, opts ...grpc.CallOption) (*ValidateWorkspaceRepoBindingResponse, error)
}

type workspaceRepoBindingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceRepoBindingServiceClient(cc grpc.ClientConnInterface) WorkspaceRepoBindingServiceClient {
	return &workspaceRepoBindingServiceClient{cc}
}

func (c *workspaceRepoBindingServiceClient) GetWorkspaceRepoBinding(ctx context.Context, in *GetWorkspaceRepoBindingRequest, opts ...grpc.CallOption) (*GetWorkspaceRepoBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkspaceRepoBindingResponse)
	err := c.cc.Invoke(ctx, WorkspaceRepoBindingService_GetWorkspaceRepoBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRepoBindingServiceClient) PutWorkspaceRepoBinding(ctx context.Context, in *PutWorkspaceRepoBindingRequest, opts ...grpc.CallOption) (*PutWorkspaceRepoBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutWorkspaceRepoBindingResponse)
	err := c.cc.Invoke(ctx, WorkspaceRepoBindingService_PutWorkspaceRepoBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRepoBindingServiceClient) DeleteWorkspaceRepoBinding(ctx context.Context, in *DeleteWorkspaceRepoBindingRequest, opts ...grpc.CallOption) (*DeleteWorkspaceRepoBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkspaceRepoBindingResponse)
	err := c.cc.Invoke(ctx, WorkspaceRepoBindingService_DeleteWorkspaceRepoBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRepoBindingServiceClient) SetWorkspaceRepoBindingCredential(ctx context.Context, in *SetWorkspaceRepoBindingCredentialRequest, opts ...grpc.CallOption) (*SetWorkspaceRepoBindingCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetWorkspaceRepoBindingCredentialResponse)
	err := c.cc.Invoke(ctx, WorkspaceRepoBindingService_SetWorkspaceRepoBindingCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRepoBindingServiceClient) ValidateWorkspaceRepoBinding(ctx context.Context, in *ValidateWorkspaceRepoBindingRequest, opts ...grpc.CallOption) (*ValidateWorkspaceRepoBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateWorkspaceRepoBindingResponse)
	err := c.cc.Invoke(ctx, WorkspaceRepoBindingService_ValidateWorkspaceRepoBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceRepoBindingServiceServer is the server API for WorkspaceRepoBindingService service.
// All implementations must embed UnimplementedWorkspaceRepoBindingServiceServer
// for forward compatibility.
//
// WorkspaceRepoBindingService manages the current workspace's repository
// binding. All RPCs derive the workspace from the X-Workspace-ID header.
// Get is available to every workspace member; the mutating RPCs require the
// caller to be a workspace owner or admin (global admins bypass).
type WorkspaceRepoBindingServiceServer interface {
	// GetWorkspaceRepoBinding returns the binding (unset when none exists)
	// plus any overlapping bindings in other workspaces. Never returns
	// credential material.
	GetWorkspaceRepoBinding(context.Context, *GetWorkspaceRepoBindingRequest) (*GetWorkspaceRepoBindingResponse, error)
	// PutWorkspaceRepoBinding creates or replaces the workspace's binding
	// configuration. Server-owned fields (credential, status, timestamps) are
	// ignored on input. Every Put resets status to UNVALIDATED: each binding
	// field (including write mode) changes what validation must prove.
	PutWorkspaceRepoBinding(context.Context, *PutWorkspaceRepoBindingRequest) (*PutWorkspaceRepoBindingResponse, error)
	// DeleteWorkspaceRepoBinding removes the binding and its stored credential.
	DeleteWorkspaceRepoBinding(context.Context, *DeleteWorkspaceRepoBindingRequest) (*DeleteWorkspaceRepoBindingResponse, error)
	// SetWorkspaceRepoBindingCredential sets or replaces the binding's PAT.
	// The PAT is write-only: it is encrypted before storage and never returned.
	SetWorkspaceRepoBindingCredential(context.Context, *SetWorkspaceRepoBindingCredentialRequest) (*SetWorkspaceRepoBindingCredentialResponse, error)
	// ValidateWorkspaceRepoBinding probes the repository with the stored
	// credential (visibility/read, branch existence, write capability, PR/MR
	// capability as required by the write mode), persists the outcome on the
	// binding, and returns it.
	ValidateWorkspaceRepoBinding(context.Context, *ValidateWorkspaceRepoBindingRequest) (*ValidateWorkspaceRepoBindingResponse, error)
	mustEmbedUnimplementedWorkspaceRepoBindingServiceServer()
}

// UnimplementedWorkspaceRepoBindingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceRepoBindingServiceServer struct{}

func (UnimplementedWorkspaceRepoBindingServiceServer) GetWorkspaceRepoBinding(context.Context, *GetWorkspaceRepoBindingRequest) (*GetWorkspaceRepoBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkspaceRepoBinding not implemented")
}
func (UnimplementedWorkspaceRepoBindingServiceServer) PutWorkspaceRepoBinding(context.Context, *PutWorkspaceRepoBindingRequest) (*PutWorkspaceRepoBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutWorkspaceRepoBinding not implemented")
}
func (UnimplementedWorkspaceRepoBindingServiceServer) DeleteWorkspaceRepoBinding(context.Context, *DeleteWorkspaceRepoBindingRequest) (*DeleteWorkspaceRepoBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkspaceRepoBinding not implemented")
}
func (UnimplementedWorkspaceRepoBindingServiceServer) SetWorkspaceRepoBindingCredential(context.Context, *SetWorkspaceRepoBindingCredentialRequest) (*SetWorkspaceRepoBindingCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWorkspaceRepoBindingCredential not implemented")
}
func (UnimplementedWorkspaceRepoBindingServiceServer) ValidateWorkspaceRepoBinding(context.Context, *ValidateWorkspaceRepoBindingRequest) (*ValidateWorkspaceRepoBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateWorkspaceRepoBinding not implemented")
}
func (UnimplementedWorkspaceRepoBindingServiceServer) mustEmbedUnimplementedWorkspaceRepoBindingServiceServer() {
}
func (UnimplementedWorkspaceRepoBindingServiceServer) testEmbeddedByValue() {}

// UnsafeWorkspaceRepoBindingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceRepoBindingServiceServer will
// result in compilation errors.
type UnsafeWorkspaceRepoBindingServiceServer interface {
	mustEmbedUnimplementedWorkspaceRepoBindingServiceServer()
}

func RegisterWorkspaceRepoBindingServiceServer(s grpc.ServiceRegistrar, srv WorkspaceRepoBindingServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkspaceRepoBindingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceRepoBindingService_ServiceDesc, srv)
}

func _WorkspaceRepoBindingService_GetWorkspaceRepoBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceRepoBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRepoBindingServiceServer).GetWorkspaceRepoBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRepoBindingService_GetWorkspaceRepoBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRepoBindingServiceServer).GetWorkspaceRepoBinding(ctx, req.(*GetWorkspaceRepoBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRepoBindingService_PutWorkspaceRepoBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutWorkspaceRepoBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRepoBindingServiceServer).PutWorkspaceRepoBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRepoBindingService_PutWorkspaceRepoBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRepoBindingServiceServer).PutWorkspaceRepoBinding(ctx, req.(*PutWorkspaceRepoBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRepoBindingService_DeleteWorkspaceRepoBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkspaceRepoBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRepoBindingServiceServer).DeleteWorkspaceRepoBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRepoBindingService_DeleteWorkspaceRepoBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRepoBindingServiceServer).DeleteWorkspaceRepoBinding(ctx, req.(*DeleteWorkspaceRepoBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRepoBindingService_SetWorkspaceRepoBindingCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWorkspaceRepoBindingCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRepoBindingServiceServer).SetWorkspaceRepoBindingCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRepoBindingService_SetWorkspaceRepoBindingCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRepoBindingServiceServer).SetWorkspaceRepoBindingCredential(ctx, req.(*SetWorkspaceRepoBindingCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRepoBindingService_ValidateWorkspaceRepoBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateWorkspaceRepoBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRepoBindingServiceServer).ValidateWorkspaceRepoBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRepoBindingService_ValidateWorkspaceRepoBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRepoBindingServiceServer).ValidateWorkspaceRepoBinding(ctx, req.(*ValidateWorkspaceRepoBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceRepoBindingService_ServiceDesc is the grpc.ServiceDesc for WorkspaceRepoBindingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceRepoBindingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agents.v1.WorkspaceRepoBindingService",
	HandlerType: (*WorkspaceRepoBindingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkspaceRepoBinding",
			Handler:    _WorkspaceRepoBindingService_GetWorkspaceRepoBinding_Handler,
		},
		{
			MethodName: "PutWorkspaceRepoBinding",
			Handler:    _WorkspaceRepoBindingService_PutWorkspaceRepoBinding_Handler,
		},
		{
			MethodName: "DeleteWorkspaceRepoBinding",
			Handler:    _WorkspaceRepoBindingService_DeleteWorkspaceRepoBinding_Handler,
		},
		{
			MethodName: "SetWorkspaceRepoBindingCredential",
			Handler:    _WorkspaceRepoBindingService_SetWorkspaceRepoBindingCredential_Handler,
		},
		{
			MethodName: "ValidateWorkspaceRepoBinding",
			Handler:    _WorkspaceRepoBindingService_ValidateWorkspaceRepoBinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agents/v1/repobinding.proto",
}
