// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: agents/v1/skill.proto

package agentsv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Skill with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Skill) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Skill with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SkillMultiError, or nil if none found.
func (m *Skill) ValidateAll() error {
	return m.validate(true)
}

func (m *Skill) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := SkillValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Description

	// no validation rules for License

	// no validation rules for Compatibility

	// no validation rules for Metadata

	// no validation rules for SizeBytes

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SkillValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SkillValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SkillValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SkillValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SkillValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SkillValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for WorkspaceId

	if len(errors) > 0 {
		return SkillMultiError(errors)
	}

	return nil
}

// SkillMultiError is an error wrapping multiple validation errors returned by
// Skill.ValidateAll() if the designated constraints aren't met.
type SkillMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SkillMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SkillMultiError) AllErrors() []error { return m }

// SkillValidationError is the validation error returned by Skill.Validate if
// the designated constraints aren't met.
type SkillValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SkillValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SkillValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SkillValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SkillValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SkillValidationError) ErrorName() string { return "SkillValidationError" }

// Error satisfies the builtin error interface
func (e SkillValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSkill.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SkillValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SkillValidationError{}

// Validate checks the field values on ListSkillsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListSkillsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSkillsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSkillsRequestMultiError, or nil if none found.
func (m *ListSkillsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSkillsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListSkillsRequestMultiError(errors)
	}

	return nil
}

// ListSkillsRequestMultiError is an error wrapping multiple validation errors
// returned by ListSkillsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListSkillsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSkillsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSkillsRequestMultiError) AllErrors() []error { return m }

// ListSkillsRequestValidationError is the validation error returned by
// ListSkillsRequest.Validate if the designated constraints aren't met.
type ListSkillsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSkillsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSkillsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSkillsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSkillsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSkillsRequestValidationError) ErrorName() string {
	return "ListSkillsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListSkillsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSkillsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSkillsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSkillsRequestValidationError{}

// Validate checks the field values on ListSkillsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSkillsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSkillsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSkillsResponseMultiError, or nil if none found.
func (m *ListSkillsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSkillsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSkills() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListSkillsResponseValidationError{
						field:  fmt.Sprintf("Skills[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListSkillsResponseValidationError{
						field:  fmt.Sprintf("Skills[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListSkillsResponseValidationError{
					field:  fmt.Sprintf("Skills[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListSkillsResponseMultiError(errors)
	}

	return nil
}

// ListSkillsResponseMultiError is an error wrapping multiple validation errors
// returned by ListSkillsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListSkillsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSkillsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSkillsResponseMultiError) AllErrors() []error { return m }

// ListSkillsResponseValidationError is the validation error returned by
// ListSkillsResponse.Validate if the designated constraints aren't met.
type ListSkillsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSkillsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSkillsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSkillsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSkillsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSkillsResponseValidationError) ErrorName() string {
	return "ListSkillsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListSkillsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSkillsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSkillsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSkillsResponseValidationError{}

// Validate checks the field values on GetSkillRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetSkillRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSkillRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSkillRequestMultiError, or nil if none found.
func (m *GetSkillRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSkillRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := GetSkillRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetSkillRequestMultiError(errors)
	}

	return nil
}

// GetSkillRequestMultiError is an error wrapping multiple validation errors
// returned by GetSkillRequest.ValidateAll() if the designated constraints
// aren't met.
type GetSkillRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSkillRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSkillRequestMultiError) AllErrors() []error { return m }

// GetSkillRequestValidationError is the validation error returned by
// GetSkillRequest.Validate if the designated constraints aren't met.
type GetSkillRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSkillRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSkillRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSkillRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSkillRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSkillRequestValidationError) ErrorName() string { return "GetSkillRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetSkillRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSkillRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSkillRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSkillRequestValidationError{}

// Validate checks the field values on GetSkillResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetSkillResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSkillResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSkillResponseMultiError, or nil if none found.
func (m *GetSkillResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSkillResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSkill()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSkillResponseValidationError{
					field:  "Skill",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSkillResponseValidationError{
					field:  "Skill",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSkill()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSkillResponseValidationError{
				field:  "Skill",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SkillMd

	if len(errors) > 0 {
		return GetSkillResponseMultiError(errors)
	}

	return nil
}

// GetSkillResponseMultiError is an error wrapping multiple validation errors
// returned by GetSkillResponse.ValidateAll() if the designated constraints
// aren't met.
type GetSkillResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSkillResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSkillResponseMultiError) AllErrors() []error { return m }

// GetSkillResponseValidationError is the validation error returned by
// GetSkillResponse.Validate if the designated constraints aren't met.
type GetSkillResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSkillResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSkillResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSkillResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSkillResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSkillResponseValidationError) ErrorName() string { return "GetSkillResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetSkillResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSkillResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSkillResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSkillResponseValidationError{}

// Validate checks the field values on CreateSkillRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSkillRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSkillRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSkillRequestMultiError, or nil if none found.
func (m *CreateSkillRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSkillRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CreateSkillRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSkillMd()) < 1 {
		err := CreateSkillRequestValidationError{
			field:  "SkillMd",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateSkillRequestMultiError(errors)
	}

	return nil
}

// CreateSkillRequestMultiError is an error wrapping multiple validation errors
// returned by CreateSkillRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateSkillRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSkillRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSkillRequestMultiError) AllErrors() []error { return m }

// CreateSkillRequestValidationError is the validation error returned by
// CreateSkillRequest.Validate if the designated constraints aren't met.
type CreateSkillRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSkillRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSkillRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSkillRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSkillRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSkillRequestValidationError) ErrorName() string {
	return "CreateSkillRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSkillRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSkillRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSkillRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSkillRequestValidationError{}

// Validate checks the field values on CreateSkillResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSkillResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSkillResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSkillResponseMultiError, or nil if none found.
func (m *CreateSkillResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSkillResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSkill()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateSkillResponseValidationError{
					field:  "Skill",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateSkillResponseValidationError{
					field:  "Skill",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSkill()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateSkillResponseValidationError{
				field:  "Skill",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateSkillResponseMultiError(errors)
	}

	return nil
}

// CreateSkillResponseMultiError is an error wrapping multiple validation
// errors returned by CreateSkillResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateSkillResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSkillResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSkillResponseMultiError) AllErrors() []error { return m }

// CreateSkillResponseValidationError is the validation error returned by
// CreateSkillResponse.Validate if the designated constraints aren't met.
type CreateSkillResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSkillResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSkillResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSkillResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSkillResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSkillResponseValidationError) ErrorName() string {
	return "CreateSkillResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSkillResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSkillResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSkillResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSkillResponseValidationError{}

// Validate checks the field values on UpdateSkillRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateSkillRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateSkillRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateSkillRequestMultiError, or nil if none found.
func (m *UpdateSkillRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateSkillRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := UpdateSkillRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSkillMd()) < 1 {
		err := UpdateSkillRequestValidationError{
			field:  "SkillMd",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateSkillRequestMultiError(errors)
	}

	return nil
}

// UpdateSkillRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateSkillRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateSkillRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateSkillRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateSkillRequestMultiError) AllErrors() []error { return m }

// UpdateSkillRequestValidationError is the validation error returned by
// UpdateSkillRequest.Validate if the designated constraints aren't met.
type UpdateSkillRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateSkillRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateSkillRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateSkillRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateSkillRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateSkillRequestValidationError) ErrorName() string {
	return "UpdateSkillRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateSkillRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateSkillRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateSkillRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateSkillRequestValidationError{}

// Validate checks the field values on UpdateSkillResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateSkillResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateSkillResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateSkillResponseMultiError, or nil if none found.
func (m *UpdateSkillResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateSkillResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSkill()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateSkillResponseValidationError{
					field:  "Skill",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateSkillResponseValidationError{
					field:  "Skill",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSkill()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateSkillResponseValidationError{
				field:  "Skill",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateSkillResponseMultiError(errors)
	}

	return nil
}

// UpdateSkillResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateSkillResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateSkillResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateSkillResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateSkillResponseMultiError) AllErrors() []error { return m }

// UpdateSkillResponseValidationError is the validation error returned by
// UpdateSkillResponse.Validate if the designated constraints aren't met.
type UpdateSkillResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateSkillResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateSkillResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateSkillResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateSkillResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateSkillResponseValidationError) ErrorName() string {
	return "UpdateSkillResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateSkillResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateSkillResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateSkillResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateSkillResponseValidationError{}

// Validate checks the field values on DeleteSkillRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteSkillRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSkillRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteSkillRequestMultiError, or nil if none found.
func (m *DeleteSkillRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSkillRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := DeleteSkillRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteSkillRequestMultiError(errors)
	}

	return nil
}

// DeleteSkillRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteSkillRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteSkillRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSkillRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSkillRequestMultiError) AllErrors() []error { return m }

// DeleteSkillRequestValidationError is the validation error returned by
// DeleteSkillRequest.Validate if the designated constraints aren't met.
type DeleteSkillRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSkillRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSkillRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSkillRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSkillRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSkillRequestValidationError) ErrorName() string {
	return "DeleteSkillRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSkillRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSkillRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSkillRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSkillRequestValidationError{}

// Validate checks the field values on DeleteSkillResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteSkillResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSkillResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteSkillResponseMultiError, or nil if none found.
func (m *DeleteSkillResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSkillResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteSkillResponseMultiError(errors)
	}

	return nil
}

// DeleteSkillResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteSkillResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteSkillResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSkillResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSkillResponseMultiError) AllErrors() []error { return m }

// DeleteSkillResponseValidationError is the validation error returned by
// DeleteSkillResponse.Validate if the designated constraints aren't met.
type DeleteSkillResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSkillResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSkillResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSkillResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSkillResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSkillResponseValidationError) ErrorName() string {
	return "DeleteSkillResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSkillResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSkillResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSkillResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSkillResponseValidationError{}
